### ISSUE TITLE
make class names editable 

### ISSUE THREAD

**Issue by jhung0** [CellProfiler/CellProfiler-Analyst#100]
You start out with class names "positive" and "negative," but you aren't able to edit them, so if you have multiple classes you're stuck with them even if those names don't make sense.

**Comment by dlogan** [comment]
You should be able to right-click in the Pos/Neg bin windows and change the names. This functionality could be more intuitive though, e.g. clicking directly on the bin titles, rather than having to discover the magical context menu.

**Comment by daviddao** [comment]
Awesome. Thanks @dlogan I will close this issue then :)
