### ISSUE TITLE
Logging panel color

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler-Analyst#105]
Lame aesthetic item; ignore/close if you want:
With the latest set of revisions, the logging panel is now black on white rather than the reverse.
![image](https://cloud.githubusercontent.com/assets/1186440/11978415/50453c6c-a940-11e5-9a39-22e4689386c7.png)
I kinda liked it the way it was :blush:. Plus I don't have to alter screenshots in my workshop slides.

**Comment by daviddao** [comment]
Got it :), that is easy to edit. If no one has a preference, I can change it back to white on black.

**Comment by braymp** [comment]
:relieved:

**Comment by daviddao** [comment]
<img width="972" alt="screen shot 2015-12-26 at 6 26 18 pm" src="https://cloud.githubusercontent.com/assets/1241240/12008267/2904ffb4-abfe-11e5-92ec-221bae1b9eae.png">
Done with 9373f9c

**Comment by daviddao** [comment]
Not working on windows

**Comment by daviddao** [comment]
added a wx.TE_RICH2 flag according to this [link](https://www.daniweb.com/programming/software-development/threads/275016/wxpython-setstyle-does-not-work-on-windows). It seems to work now on Windows with the latest commit 090cec1
