### ISSUE TITLE
PlateViewer: wx 3.0 layout issue

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler-Analyst#106]
By upgrading to wx 3.0, the PlateViewer layout is a bit messed up upon opening:
![image](https://cloud.githubusercontent.com/assets/1186440/11978504/ee9e2bd0-a940-11e5-9882-94d99e35568a.png)
The drop-downs now takes the length of the longest entry, it appears. Formerly, these drop-downs were clipped to the same width:
![image](https://cloud.githubusercontent.com/assets/1186440/11978535/384fcffe-a941-11e5-9c61-59c9676db285.png)
I'm not sure if this is easily correctable...

**Comment by daviddao** [comment]
fixed with 33c6707ba54004fcead26456c97405f4ac526cc8 
<img width="912" alt="screen shot 2016-01-11 at 2 18 45 pm" src="https://cloud.githubusercontent.com/assets/1241240/12243801/684fe310-b86e-11e5-9d0f-be09d8472e1f.png">
