### ISSUE TITLE
Zooming images

### ISSUE THREAD

**Issue by daviddao** [CellProfiler/CellProfiler-Analyst#111]
When changing the zoom on the tiles in the classifier, it also changes the zoom for the image viewer without actually zooming into the image. Hence the image doesn't have a scrollbar anymore.

![screen shot 2016-01-13 at 4 50 27 pm](https://cloud.githubusercontent.com/assets/1241240/12309051/82590206-ba16-11e5-8410-3b288e1adeb3.png)

**Comment by jhung0** [comment]
Should be fixed in the image classification branch. I just kept scale = 1 when viewing the full image.

**Comment by daviddao** [comment]
Thanks I will have a look.

**Comment by daviddao** [comment]
Great! It works after 543c40d and e0655fa .
