### ISSUE TITLE
Error if fetching objects but no object table

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler-Analyst#116]
If a props file references an image table, but no object table, fetching objects in Classifier fails:
```
￼ File "C:\Trunk\pull_requests\CellProfiler-Analyst\CellProfiler-Analyst.py", line 531, in <module>
  app.MainLoop()
File "C:\Python27\Lib\site-packages\wx-3.0-msw\wx\_core.py", line 8657, in MainLoop
  wx.PyApp.MainLoop(self)
File "C:\Python27\Lib\site-packages\wx-3.0-msw\wx\_core.py", line 7952, in MainLoop
  return _core_.PyApp_MainLoop(*args, **kwargs)
￼ File "C:\Trunk\pull_requests\CellProfiler-Analyst\cpa\classifier.py", line 844, in OnFetch
  obKeys = dm.GetRandomObjects(nObjects)
￼ File "C:\Trunk\pull_requests\CellProfiler-Analyst\cpa\datamodel.py", line 119, in GetRandomObjects
  return [self.GetRandomObject() for i in xrange(N)]
￼ File "C:\Trunk\pull_requests\CellProfiler-Analyst\cpa\datamodel.py", line 97, in GetRandomObject
  obIdx = randint(1, self.obCount)
File "C:\Python27\Lib\random.py", line 242, in randint
  return self.randrange(a, b+1)
File "C:\Python27\Lib\random.py", line 218, in randrange
  raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)

ValueError: empty range for randrange() (1,1, 0)
```
Probably better to have Classifier check if an object table exists, and provide an warning/error msg if not, or don't even open Classifier at all (with a msg as to why).

**Comment by jhung0** [comment]
Is that MySQL? Sqlite? Can you send the properties file?

**Comment by jhung0** [comment]
My test examples work, so I'm not sure what's happening.

**Comment by braymp** [comment]
This is for regular per-object classification (i.e., not the image classification branch), so this probably has been a long standing bug.

**Comment by jhung0** [comment]
Oh I see. I might have changed some error messages to accommodate image
classification.

**Comment by braymp** [comment]
I'm actually not sure if there ever was an error msg... :smile:

**Comment by jhung0** [comment]
There should be one now

**Comment by jhung0** [comment]
Can you check this (using the image classification branch)?

**Comment by braymp** [comment]
Now CPA errors upon opening at https://github.com/CellProfiler/CellProfiler-Analyst/blob/image-classification/cpa/properties.py#L471. 

Having no object table is fine for CPA, but it should only error if using Classifier in object classification mode.

**Comment by jhung0** [comment]
Ok I misunderstood. Try it now
