### ISSUE TITLE
Display multiple images in ImageViewer 

### ISSUE THREAD

**Issue by jhung0** [CellProfiler/CellProfiler-Analyst#119]
Currently when you click ImageViewer, you just get the option of choosing what number image you want to see. For classifier, you can now display images for image classification and that should be implemented in image viewer (like Zegami).

**Comment by daviddao** [comment]
PlateViewer allows you to look at images for each well, and multiple plates. Awesome feature but very slow currently. 
![screen shot 2016-01-16 at 7 27 49 pm](https://cloud.githubusercontent.com/assets/1241240/12375244/55df2b1a-bc87-11e5-9e19-b55d794f71bc.png)

**Comment by daviddao** [comment]
@mrohban proposed to add filters for the image gallery viewer which are based on the meta data
- [ ] filtering images

**Comment by dlogan** [comment]
+1 to using metadata rather than the ImageNumber for image choosing. The average user does nor know how to acquire the ImageNumber from the database but they may know by the metadata.

**Comment by daviddao** [comment]
Done with #124 !

**Comment by dlogan** [comment]
I figured, nice!

**Comment by AnneCarpenter** [comment]
It is a sight to behold. SO nice.
