### ISSUE TITLE
Limit to one classifier instance?

### ISSUE THREAD

**Issue by daviddao** [CellProfiler/CellProfiler-Analyst#123]
@ljosa @afraser: @jhung0 and I were curious about the implementation of the Classifier window as a singleton. Is there a reason, we can only run one instance of Classifier at a time? 
Given multiple instances, we would be able to train different classifiers at the same time and compare them with each other.

**Comment by afraser** [comment]
It's been a long time, but I doubt there's any reason other than lack of foresight. I probably did it this way because I thought it'd make development simpler.

**Comment by daviddao** [comment]
Thanks for the quick response :)

**Comment by afraser** [comment]
np. Happy hacking!

**Comment by braymp** [comment]
That would be neat. Also, I've had two instances of CPA (= 1 Classifier
each) and have been able to drag/drop tiles from one Classifier instance to
the other; v. convenient at times.
