### ISSUE TITLE
Classifier: Small UI widget arrangement issues

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler-Analyst#125]
This is how the initial Classifier UI looks on Windows; it's fine except for 2 things:
![image](https://cloud.githubusercontent.com/assets/1186440/12455442/bf402b88-bf69-11e5-9052-8b4b9a7136aa.png)
* The "Add new class" button needs more space at the bottom.
* The "Score Image" button needs to be wider, perhaps by making the Classifier UI a bit wider overall.

**Comment by daviddao** [comment]
Fixed with commit  07e0832 . CPA looks on Windows Vista as follows: 

![untitled](https://cloud.githubusercontent.com/assets/1241240/12470396/c502296a-bfc1-11e5-86d7-f52dc2044ddd.png)

**Comment by braymp** [comment]
"Add class" button looks a bit better, but "Score Image" still too small (Win7):
![image](https://cloud.githubusercontent.com/assets/1186440/12483276/f98fb14c-c021-11e5-83b4-05b6ac4c211e.png)

**Comment by braymp** [comment]
Also, I noticed that it looks fine on my laptop screen, but as above on my monitor....

**Comment by jhung0** [comment]
Still a problem?

**Comment by braymp** [comment]
Seems fine now. Closing.
![image](https://cloud.githubusercontent.com/assets/1186440/15542647/9d83b9b6-225f-11e6-9322-e787fcef609e.png)
