### ISSUE TITLE
Widen the CPA UI

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler-Analyst#126]
Similar to #125: The CPA UI needs to be wider overall, as the density/boxplot icons on the right are not visible on startup (at least on Windows)
![image](https://cloud.githubusercontent.com/assets/1186440/12455581/3d5d5f40-bf6a-11e5-9fbb-a9d4155a78fa.png)

**Comment by AnneCarpenter** [comment]
This will be improved somewhat when ImageViewer is subsumed into
ImageGallery; from the screenshot this looks like two and a half items are
off-screen, not just one.

**Comment by daviddao** [comment]
@AnneCarpenter is right. I ported ImageViewer functionality into ImageGallery. Now it fits: 
![untitled](https://cloud.githubusercontent.com/assets/1241240/12466429/95728d8a-bfa2-11e5-8783-0263eb14b043.png)

**Comment by braymp** [comment]
Still looks truncated on my screen:
![image](https://cloud.githubusercontent.com/assets/1186440/12482186/3908abb8-c01c-11e5-9046-4a17b2bab861.png)

**Comment by braymp** [comment]
According to [this](http://stackoverflow.com/questions/12607460/wxpython-minimal-size-of-frame-with-a-panel), can wx.frame.SetSizeHints help?

**Comment by jhung0** [comment]
Still have this problem?

**Comment by braymp** [comment]
Seems OK now:
![image](https://cloud.githubusercontent.com/assets/1186440/14931917/93f0dae0-0e3d-11e6-854d-7365efb31fdc.png)
