### ISSUE TITLE
Make image classification a menu item in Classifier?

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler-Analyst#127]
I'm wondering whether it makes sense to simply have the user select whether they want to do per-object or per-image classification from the Classifier UI. Currently, it needs to be set as a properties field, which is workable, but not as intuitive. 

I'm imagining a menu item (not sure what to call it) that has two options: per-cell (default) and per-image. if a user toggles between one and the other, I think the following should happen since the two are mutually exclusive:
* Clear the current training set; give the user the option to save first.
* Clear the current classifier; give option to save first?
* Revert to the default two classes with default naming.

@daviddao, @jhung0: Any thoughts?

**Comment by jhung0** [comment]
Yeah it's not going to be that easy. The closest thing would be some button that generates a new properties.
