### ISSUE TITLE
Limit on number of rules in SQLite?

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler-Analyst#129]
For Fast Gentle Boosting, our manual says this:
<blockquote>
SQLite Limitation: With our current implementation, SQLite limits the number of rules that can be used depending on how many classes you have. E.g.: For 2 classes, no more than 23 rules can be used, for 3 classes, no more than 18.
</blockquote>
@daviddao: Is this still the case? If so, why? Also, do any of the other classifiers have differences in performance between SQLite and MySQL?

**Comment by LeeKamentsky** [comment]
I think that CPA generates a select command that encodes the rules. More rules = longer statement. Probably hits some sort of limit at some point.

**Comment by jhung0** [comment]
The other classifiers should not differentiate between sqlite and mysql

**Comment by daviddao** [comment]
Yes, the bottleneck for Fast Gentle Boosting is this [line](https://github.com/CellProfiler/CellProfiler-Analyst/blob/master/cpa/multiclasssql_legacy.py#L58) - when classifying and fetching from the database.

I don't know of any performance differences between sqlite and mysql

**Comment by braymp** [comment]
Great, thanks!
