### ISSUE TITLE
ImageGallery error

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler-Analyst#135]
I dragged an image in ImageGallery from the top window to the bottom (naively, without any good reason!), and then clicked on the thumbnail and got this error:

```
An error occurred in the program:
Exception: Failed to load coordinates for object key ImageNumber:1, ParasitesGood_Number_Object_Number:-1. This may indicate a problem with your per-object table.
You can check your per-object table "Nil_2015_10_29_Thailand_v2Per_ParasitesGood" in TableViewer

Traceback (most recent call last):
  File "/Applications/CellProfiler Analyst.app/Contents/Resources/lib/python2.7/cpa/imagetile.py", line 176, in OnDClick
  File "/Applications/CellProfiler Analyst.app/Contents/Resources/lib/python2.7/cpa/dbconnect.py", line 654, in GetObjectCoords
```

**Comment by daviddao** [comment]
True, the first window is for images only, the bottom one for objects. I agree, images shouldn't be draggable at all!

**Comment by braymp** [comment]
Previously, you could drag objects out of ImageViewer into Classifier; a nice feature. Is that still the case?

**Comment by daviddao** [comment]
Yes - everything is draggable. Which is great but also dangerous because one can now drag and drop images and objects into the classifier. Each image thumbnail has as object key (imagekey, 1).

**Comment by AnneCarpenter** [comment]
It sounds like the fix here would be for the 'receiving' window to reject particular types it can't accept (e.g., keep it still possible to pick up and drag a whole-image, but the object classifier should refuse to accept it?) Or do we indeed want to prevent picking up whole-images in the first place? Or is this super complicated - can classify objects AND whole-images these days?

**Comment by DavidStirling** [comment]
Done. Gallery images can no longer be moved into object bins. The objects bin still behaves as normal.
