### ISSUE TITLE
ImageGallery individual image 

### ISSUE THREAD

**Issue by jhung0** [CellProfiler/CellProfiler-Analyst#136]
go to imagegallery, click fetch for an individual image
choose cancel -> you get a window that's mostly white but it shouldn't show any window

**Comment by daviddao** [comment]
True, i imported the legacy ImageViewer code from the old CPA 2.0 (see image) which opens the ImageViewer application.

<img width="856" alt="screen shot 2016-01-22 at 10 34 21 am" src="https://cloud.githubusercontent.com/assets/1241240/12514928/d3496c44-c0f3-11e5-99a9-4bf31992f1b5.png">

**Comment by jhung0** [comment]
yeah it's not a big deal

**Comment by daviddao** [comment]
Fixed with adc19f9cfd44ef42a0c1918840732770f5a52a6f
