### ISSUE TITLE
Classifier: top features

### ISSUE THREAD

**Issue by jhung0** [CellProfiler/CellProfiler-Analyst#137]
We want to make it more clear that the "top features" shown are just for display only... so instead of "with" we can say "show" or "display"

**Comment by daviddao** [comment]
:+1:

**Comment by braymp** [comment]
I was just thinking about this: I think "display" is appropriate, except for FastGentleBoosting.

**Comment by jhung0** [comment]
I changed it to display, but I guess we'd need to make an exception for FastGentleBoosting

**Comment by daviddao** [comment]
Fixed with 144cd2b
