### ISSUE TITLE
Image gallery images are mysteriously greener than resized originals

### ISSUE THREAD

**Issue by daviddao** [CellProfiler/CellProfiler-Analyst#141]
Somehow, when fetching images with ImageGallery on the example_cpa dataset, the thumbnails appear to be much greener. 

<img width="529" alt="screen shot 2016-01-22 at 4 02 37 pm" src="https://cloud.githubusercontent.com/assets/1241240/12522963/d657939c-c121-11e5-99dd-f86463db13db.png">

**Comment by dlogan** [comment]
Probably related to #140

**Comment by daviddao** [comment]
Fixed with 832102eae6eea7eb58397b7400df0450260bc894 , it turned out that 
```
scipy.resize()
```

which I was using originally for resizing fetched images is not equivalent with wxPython's 

```
wxImage.rescale()
```
