### ISSUE TITLE
Starting CPA without properties file

### ISSUE THREAD

**Issue by daviddao** [CellProfiler/CellProfiler-Analyst#144]
From @AnneCarpenter : Right now a new user starts up CPA and can't do anything without a properties file... a bit rude to start that way but it's a necessity because they really can't do anything without it.

BUT, it would be nice to point the user to the URL where they can get example data/properties. Is it possible to put that URL somehow in the dialog box (I guess not?) - but is there some other way to provide this info to the user so they are pointed in the right direction?

**Comment by daviddao** [comment]
Closed with b59e487a018a4bab3cefb4e6c0613c0873958b29

**Comment by braymp** [comment]
Just gave this a try; the dialog box appears behind the CPA splash screen, so it's easy to miss. Is there a way to destroy the CPA prior to showing the dialog?

**Comment by jhung0** [comment]
I noticed that my machine doesn't show a splash screen at all

**Comment by jhung0** [comment]
@daviddao should we just remove the splash screen?

**Comment by braymp** [comment]
I'm completely and utterly biased, but I've always liked it... :smile:

**Comment by AnneCarpenter** [comment]
@0x00B1 has an opinion on splash screens... they must die.

**Comment by DavidStirling** [comment]
Splashy problems are fixed in WX4
