### ISSUE TITLE
Gating doesn't work 

### ISSUE THREAD

**Issue by daviddao** [CellProfiler/CellProfiler-Analyst#146]
Gating doesn't work currently in CPA ! @ljosa @afraser ? Do you know more about this functionality? What is it supposed to do? How does it differ from filter? 

<img width="712" alt="screen shot 2016-01-22 at 9 22 30 pm" src="https://cloud.githubusercontent.com/assets/1241240/12527693/5ce45d2e-c14e-11e5-9788-abeeef24b311.png">

**Comment by jhung0** [comment]
There's nothing about it in the manual ![snip20160122_10](https://cloud.githubusercontent.com/assets/9591682/12527700/8bece14a-c14e-11e5-8004-c9296f831726.png)

**Comment by ljosa** [comment]
I have no idea. @AnneCarpenter might know.

**Comment by LeeKamentsky** [comment]
You should be able to draw a gate on a scattergram or histogram and then display only cells in that gate in a subsequent scattergram or histogram. I just tried this in an old version of CPA and it worked. I opened a scattergram, set it up to display "Nuclei_Location_Center_X" and "Nuclei_Location_Center_Y". I selected "Create New Gate" from the "gate" dropdown. I named the gate "mygate" and then used the rectangle tool that's invoked to select a spatial region on the plot (x = 200 to 400, roughly). I then selected "mygate" from the "filter" menu in the boxplot and set the boxplot up to display Cells_Location_Center_X. It only plotted cells from x = 200 to x = 400 as you can see below:
![image](https://cloud.githubusercontent.com/assets/660469/12556379/95212a9e-c353-11e5-8e7b-9be237b7a1aa.png)
![image](https://cloud.githubusercontent.com/assets/660469/12556387/9c92fa46-c353-11e5-9aae-c2fe2ae76634.png)

**Comment by daviddao** [comment]
Thank you all! That was very helpful!

**Comment by daviddao** [comment]
Should work with 2ee0164

**Comment by AnneCarpenter** [comment]
😁
