### ISSUE TITLE
ValueError on classifying image

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler-Analyst#147]
Use the following SQLite db, props file and training set, and do the following:
* Load training set
* Train with RandomForest
* Open an image (I was using image number 14 when it happened), and use Classify > Classify image.

I then got the error below.
```
ValueError: Input contains NaN, infinity or a value too large for dtype('float32').

Traceback (most recent call last):
  File "C:\Trunk\cellProfiler-analyst\cpa\imageviewer.py", line 504, in OnClassifyImage
    classHits = classifier.ScoreImage(self.img_key)
  File "C:\Trunk\cellProfiler-analyst\cpa\classifier.py", line 1493, in ScoreImage
    classHits[bin.label] = self.algorithm.FilterObjectsFromClassN(clNum + 1, [imKey])
  File "C:\Trunk\cellProfiler-analyst\cpa\generalclassifier.py", line 73, in FilterObjectsFromClassN
    return multiclasssql.FilterObjectsFromClassN(obClass, self, obKeysToTry, uncertain)
  File "C:\Trunk\cellProfiler-analyst\cpa\multiclasssql.py", line 132, in FilterObjectsFromClassN
    predicted_classes = classifier.Predict(cell_data)
  File "C:\Trunk\cellProfiler-analyst\cpa\generalclassifier.py", line 116, in Predict
    predictions = self.classifier.predict(test_values)
  File "C:\Python27\lib\site-packages\sklearn\ensemble\forest.py", line 498, in predict
    proba = self.predict_proba(X)
  File "C:\Python27\lib\site-packages\sklearn\ensemble\forest.py", line 537, in predict_proba
    X = self._validate_X_predict(X)
  File "C:\Python27\lib\site-packages\sklearn\ensemble\forest.py", line 319, in _validate_X_predict
    return self.estimators_[0]._validate_X_predict(X, check_input=True)
  File "C:\Python27\lib\site-packages\sklearn\tree\tree.py", line 365, in _validate_X_predict
    X = check_array(X, dtype=DTYPE, accept_sparse="csr")
  File "C:\Python27\lib\site-packages\sklearn\utils\validation.py", line 398, in check_array
    _assert_all_finite(array)
  File "C:\Python27\lib\site-packages\sklearn\utils\validation.py", line 54, in _assert_all_finite
    " or a value too large for %r." % X.dtype)
```
[DefaultDB.db.txt](https://github.com/CellProfiler/CellProfiler-Analyst/files/103469/DefaultDB.db.txt)
[DefaultDB.properties.txt](https://github.com/CellProfiler/CellProfiler-Analyst/files/103467/DefaultDB.properties.txt)
[MyTrainingSet.txt](https://github.com/CellProfiler/CellProfiler-Analyst/files/103466/MyTrainingSet.txt)

**Comment by jhung0** [comment]
I can't get the properties file to locate the db file, but I made a change
that should fix it

**Comment by braymp** [comment]
Haven't had this happen again, so I'll close.

**Comment by tedstertm** [comment]
I'm having an identical issue when I run score all on my image set. 

What was the solution to this?

I'm running the OSX nightly.

[DefaultDB_MyExpt.properties.txt](https://github.com/CellProfiler/CellProfiler-Analyst/files/196981/DefaultDB_MyExpt.properties.txt)

**Comment by daviddao** [comment]
@tedstertm which version of CPA are you using?

**Comment by tedstertm** [comment]
2.2.1. I've tried to use 2.0 previously and have never got it working the
way I needed. I have done this in the past and have had it work perfectly
fine.

**Comment by daviddao** [comment]
We cannot access your data. Can you share your per_object table? Also can you try using FastGentleBoosting instead of Random Forest? I suspect that the per_object table contains empty values (NaNs)

**Comment by tedstertm** [comment]
FastGentleBoosting works for this. You may be correct about empty values.
My per_object table is quite large (30MB), is there an alternative means to
send it?

**Comment by daviddao** [comment]
You can share it either on google drive or with a dropbox link. Can you also share the per_image table so we can reproduce the issue?

**Comment by tedstertm** [comment]
Here's everything except the images.

https://drive.google.com/folderview?id=0ByJw-tIz3E9mel8zOXZjQkZLTFU&usp=sharing

**Comment by daviddao** [comment]
Thanks a lot for reporting! We look into it :)

**Comment by jhung0** [comment]
@tedstertm  I think I fixed it. Could you try with be0bf9c?

**Comment by daviddao** [comment]
Jenkins is building the new version, it should be possible to download CPA with be0bf9c in a couple of minutes.

**Comment by tedstertm** [comment]
It works now. Thanks for your help!

**Comment by daviddao** [comment]
Thanks @jhung0 !
@tedstertm Feel free to report issues to us at anytime! I am re-closing this now.
