### ISSUE TITLE
Classifier: Blank space left if drag/dropping an image tile

### ISSUE THREAD

**Issue by jhung0** [CellProfiler/CellProfiler-Analyst#148]
From @braymp 
While using a Classifier, I was doing the usual drag/dropping from the unclassified bin to the pos/neg bins. I noticed that in some cases when I dropped a tile, the remaining tiles in the unclassified bin didn't move over to fill the gap but instead left a blank space where the tile was. E.g. see screenshot (space where the 1st tile would be).

![image](https://cloud.githubusercontent.com/assets/1186440/12557568/707e4afe-c359-11e5-9294-ab35bc5f6785.png)

**Comment by jhung0** [comment]
This is a known issue, and I guess we decided it wasn't important enough to figure out why it does this.

**Comment by daviddao** [comment]
it's a legendary bug since the beginning of CPA 2.1 - let's see if I can figure it out.

**Comment by daviddao** [comment]
Hopefully fixed with 3e442176b16b9fae385735d94936317b3657a9c9
