### ISSUE TITLE
Suggested changes to 'Evaluation' menu item/button

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler-Analyst#149]
Suggestions (@daviddao, what do you think?):
* Change the 'Evaluation' button and menu item text to 'Performance'
*  The 'Performance' menu item should have the following sub-items: (1) 'Generate report...' (which does the same action as the button), (2) 'Report Type', with sub-menu items 'Classification Report' and 'Confusion Matrix'

Also, is there a reason that FGB doesn't generate a precision/recall/F1 matrix (for the current # of rules) as the other classifiers do?

**Comment by jhung0** [comment]
FGB is not part of scikit learn, so it doesn't have the same functionality as the other classifiers. It would take special effort to make sure FGB has the same functionalities, and in my opinion we should discourage use of FGB as much as possible. It's just there for people who really want to use the old CPA.

**Comment by braymp** [comment]
@daviddao mentioned that 'Performance' was already batted around and rejected. So I'm fine with 'Evaluation' (probably 'Evaluate' to keep the same verb tense with the other buttons). However, I still vote for the sub-menu options.

The problem I'm debating in my head is that I think the sub-item which does the same action as the button (bullet 1 above) should have the same text label as the button. But if we have 'Evaluate' for this sub-item, then what does the menu itself get called? It seems funny to have 'Evaluate' as the menu item and then 'Evaluate' again as the 1st item. 

Does that make sense? Any thoughts?

**Comment by jhung0** [comment]
The menu does not do the same thing as the button. We just want the menu items to list options for evaluation metrics. Maybe we can change the button to Evaluate and keep the Evaluation menu item.
