### ISSUE TITLE
Classifier: Disable "Evaluate" button if "Train" has not been pressed first

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler-Analyst#151]
I noticed  that after loading a training set, both the "Train" and "Evaluate" buttons become active. However, if no classifier has been generated, there's nothing to evaluate.

**Comment by jhung0** [comment]
Train trains on all annotated data, but evaluate does cross validation by taking the annotated data and separating it into training and tests sets.

**Comment by braymp** [comment]
Cross-validation implies that a classifier has already been produced, correct? In this case, I'm starting fresh, and no classifier has been made. In that case, the user hasn't requested the classifier and there's no visual feedback that a classifier exists yet. I don't think that's the best approach since it's not intuitive as to what is being evaluated. 

Another way to put it: classifier.XValidatePredict uses self.classifier, but where did the classifier come from? The user should have produced it via Train.

**Comment by jhung0** [comment]
What do you mean? The classifier is the one that's chosen (RandomForest, SVC, etc.), and the cross validation evaluates the chosen classifier.

**Comment by braymp** [comment]
Jane and David clarified that the classifiers used in 'Train' and 'Evaluate' are not the same; the latter is an approximation of the former.
