### ISSUE TITLE
Training set save options: CSV only?

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler-Analyst#155]
Training sets can now be saved in the original txt file format or as a csv. I assume that both formats are available for loading due to backwards compatibility, but is there any reason why we shouldn't force saving to CSV only?

**Comment by daviddao** [comment]
Another reason is that saving as CSV currently saves also the CP feature vector for each object while trainingSet.txt just saves the object ids with their labels. In that sense it is a smaller and faster saving option. Other than that, there is no reason to keep trainingSet.txt besides the backwards compatibility

**Comment by braymp** [comment]
I thought that the .txt option also saved a hash of the feature vector, at the bottom?

**Comment by daviddao** [comment]
It used to, I removed the hash in order to save memory. Is the hash used somewhere ? I couldn't find any code in CPA, which processes it.

**Comment by braymp** [comment]
Below is the rationale that might help, from an old email chain (turns out it's not for the features):
<blockquote>
I wanted to bring up something that I think the IADs have run into on occasion: The need to renumber objects used in a training set when a new assay has changed things. One example is a case where the IAD has produced a different object numbering but not (typically) a substantially different object position. Depending on the assay, this can cost hours of time for the collaborator to re-training to the new assay. My centrosome project is an example of this, in which I have two tables, but have yet to have my collaborator re-train on the new one.
</blockquote>
<blockquote>
We have some ideas how to decorate the
training set with object positions, then use those to validate
training sets on loading to make them automatically update with the
closest object when the numbers change.
</blockquote>
<blockquote>
It should also be possible to handle image renumberings, as long the
image content doesn't change, but for that we need an SHA1 hash or
similar to be computed in CP or at least loaded into the DB somehow
for each image.
</blockquote>
<blockquote>
We need to use either image paths or image hashes to handle the case
where images get renumbered.  Paths aren't very stable, so I'd prefer
hashes.  CPA never has to compute them.  We can make the hash-using
code in CPA optional, and not handle image renumbering if they're not
present.
</blockquote>

**Comment by daviddao** [comment]
I see, thanks a lot for the clarifications. I revisited the code and noticed, that I indeed didn't remove the hash because of similar reasons. For now, I would like to keep it this way. But we can reorder loading and saving such that CSV would be the default option?

**Comment by braymp** [comment]
Sure, I would vote for the following changes to the File menu (to simplify things):
* "Load training set" -> The "Open" dialog that opens has "Text files (*.txt), CSV (*.csv)" as the default view, along with "All files (*.*)". I don't think you need separate menu items for each, as the code path to take can be figured out from the extension of the loaded file.
* "Save training set" -> Saves as CSV (and is the only format allowed)

**Comment by daviddao** [comment]
Sounds like an elegant solution. I'm sold! :)

**Comment by braymp** [comment]
Addressed by #156.
