### ISSUE TITLE
Windows Image Gallery fetch by filter window too small

### ISSUE THREAD

**Issue by jhung0** [CellProfiler/CellProfiler-Analyst#157]
In image gallery, when you fetch by filter, the window you get is too small.
![cpa_imagegallery_filter](https://cloud.githubusercontent.com/assets/9591682/12705294/9e02439e-c83c-11e5-86b3-d5f3fc7d4f4d.PNG)

**Comment by daviddao** [comment]
Note: Windows 10

**Comment by braymp** [comment]
Same on my Windows 7 box.
![image](https://cloud.githubusercontent.com/assets/1186440/12718328/f25c45a0-c8bb-11e5-973d-b7225f4ec6cf.png)
Although the above is on my monitor; on a smaller laptop screen, it looks fine.

**Comment by daviddao** [comment]
@jhung0 any ideas why this could be the case?

**Comment by jhung0** [comment]
You can't set the size to like 2 times bigger?

**Comment by DavidStirling** [comment]
Fixed in 3.0
