### ISSUE TITLE
Whole image display in Classifier

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler-Analyst#160]
It appears that Classifier yields a different display if <code>image_width</code>/<code>image_height</code> are placed in the props file, <code>claasification_type</code> is set to 'image'; properties file attached.

If <code>image_width</code>/<code>image_height</code> are defined (image displayed as thumbnails):
![image](https://cloud.githubusercontent.com/assets/1186440/12889283/2d5dda52-ce4c-11e5-973c-47bb0077cfd0.png)

If <code>image_width</code>/<code>image_height</code> are not defined (image displayed at full size):
![image](https://cloud.githubusercontent.com/assets/1186440/12889354/77ec69f8-ce4c-11e5-890b-4128f007a826.png)

[2015_10_05_DrugRepurposing_GolubLab_Broad_qc_2016_02_02_u2os_a549_24hr_48hr_bioactives.properties.txt](https://github.com/CellProfiler/CellProfiler-Analyst/files/121726/2015_10_05_DrugRepurposing_GolubLab_Broad_qc_2016_02_02_u2os_a549_24hr_48hr_bioactives.properties.txt)

**Comment by jhung0** [comment]
What do you expect should happen? 
If you want images scaled like in the first example, you should input image width and height.

**Comment by braymp** [comment]
Why can it not determine it from the db if not present? I'd prefer the user
not have to edit the props file. FYI: Lee determined that it is not
straightforward to have CellProfiler do it in ExporToDB....

**Comment by LeeKamentsky** [comment]
The primary issue is that there is a corner case where images of different sizes might be analyzed - you just can't count on the sizes to all be the same. The secondary issue is that CellProfiler has five stages in which it does its work: prepare_run, prepare_group, run, post_group and post_run. The properties file is written in prepare_run and no image files are loaded during that stage (and it would be great if I could keep it that way). I would have to put in a hack to look for some FileName and PathName measurement, construct a file name and read the file to get its size - not a good idea to burden ExportToDatabase with knowing how to do that and not good to pick randomly without the user's knowledge from among file names.

**Comment by jhung0** [comment]
same problems for CPA, so I guess it's up to the user

**Comment by daviddao** [comment]
@braymp @LeeKamentsky  @jhung0 Any updates on this issue? Should I close it?
