### ISSUE TITLE
Pickle CPA classifier with feature names

### ISSUE THREAD

**Issue by daviddao** [CellProfiler/CellProfiler-Analyst#161]
From @LeeKamentsky. In order to include CPA classifiers in CPA, we need to pickle feature names of the trainingset

**Comment by jhung0** [comment]
done 298648a2e35c774cdd7b4f31427d67b1b33226b6

**Comment by daviddao** [comment]
Awesome thanks a lot @jhung0 !

**Comment by LeeKamentsky** [comment]
Thx @jhung0 that was great. Time for me to get to work.
