### ISSUE TITLE
Add unique prefix to image classification view

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler-Analyst#162]
Currently, enabling image classification in MySQL creates a view with the name "ObjectTable". If two CPA instances were opened, referencing the same db and performing image classification, one view would overwrite the other.

The view (and tmp table in SQLite) should be prefixed with the image table prefix, i.e, the string prior to "_Per_Image"

**Comment by jhung0** [comment]
How about how the mysql does it (adding a _AsObjectTable to the image table
name)? I think it'd be too much trouble finding the prefix.

**Comment by jhung0** [comment]
Sorry nevermind that's not how mysql does it. But anyway does that work for
you?

**Comment by braymp** [comment]
The approach I took in my original script was pretty straightforward:
```
view_identifier = "ImageAsObjectTable"
new_view_name = "_".join((re.split("_Per",image_table)[0],view_identifier))
```
But I think I like tacking the "ObjectTable" to the per-image table name. Go for it!

**Comment by jhung0** [comment]
done bafc7c5

**Comment by daviddao** [comment]
Guess I can close this issue? Feel free to reopen if not solved.
