### ISSUE TITLE
DBConnect.GetColnamesForClassifier returns blobs

### ISSUE THREAD

**Issue by LeeKamentsky** [CellProfiler/CellProfiler-Analyst#165]
I am getting the pickled feature names which come from trainingset.colnames. I believe they get generated by DBConnect.GetColnamesForClassifier. The list is appended below. You can see some thumbnail measurements, e.g. Image_Thumbnail_OrigAGP. The datatype for a thumbnail is a blob - I think the actual text is generated here: https://github.com/CellProfiler/CellProfiler-Analyst/blob/298648a2e35c774cdd7b4f31427d67b1b33226b6/cpa/dbconnect.py#L1040, so I'm not sure exactly how they are represented.

Anyway, DBConnect.GetColnamesForClassifier should exclude those.

Image_x_loc
Image_y_loc
Image_Frame_OrigAGP
Image_Frame_OrigDNA
Image_Frame_OrigER
Image_Frame_OrigMito
Image_Frame_OrigRNA
Image_Group_Index
Image_Group_Number
Image_Height_OrigAGP
Image_Height_OrigDNA
Image_Height_OrigER
Image_Height_OrigMito
Image_Height_OrigRNA
Image_ImageQuality_Correlation_OrigAGP_10
Image_ImageQuality_Correlation_OrigAGP_2
Image_ImageQuality_Correlation_OrigAGP_20
Image_ImageQuality_Correlation_OrigAGP_5
Image_ImageQuality_Correlation_OrigDNA_10
Image_ImageQuality_Correlation_OrigDNA_2
Image_ImageQuality_Correlation_OrigDNA_20
Image_ImageQuality_Correlation_OrigDNA_5
Image_ImageQuality_Correlation_OrigER_10
Image_ImageQuality_Correlation_OrigER_2
Image_ImageQuality_Correlation_OrigER_20
Image_ImageQuality_Correlation_OrigER_5
Image_ImageQuality_Correlation_OrigMito_10
Image_ImageQuality_Correlation_OrigMito_2
Image_ImageQuality_Correlation_OrigMito_20
Image_ImageQuality_Correlation_OrigMito_5
Image_ImageQuality_Correlation_OrigRNA_10
Image_ImageQuality_Correlation_OrigRNA_2
Image_ImageQuality_Correlation_OrigRNA_20
Image_ImageQuality_Correlation_OrigRNA_5
Image_ImageQuality_FocusScore_OrigAGP
Image_ImageQuality_FocusScore_OrigDNA
Image_ImageQuality_FocusScore_OrigER
Image_ImageQuality_FocusScore_OrigMito
Image_ImageQuality_FocusScore_OrigRNA
Image_ImageQuality_LocalFocusScore_OrigAGP_10
Image_ImageQuality_LocalFocusScore_OrigAGP_2
Image_ImageQuality_LocalFocusScore_OrigAGP_20
Image_ImageQuality_LocalFocusScore_OrigAGP_5
Image_ImageQuality_LocalFocusScore_OrigDNA_10
Image_ImageQuality_LocalFocusScore_OrigDNA_2
Image_ImageQuality_LocalFocusScore_OrigDNA_20
Image_ImageQuality_LocalFocusScore_OrigDNA_5
Image_ImageQuality_LocalFocusScore_OrigER_10
Image_ImageQuality_LocalFocusScore_OrigER_2
Image_ImageQuality_LocalFocusScore_OrigER_20
Image_ImageQuality_LocalFocusScore_OrigER_5
Image_ImageQuality_LocalFocusScore_OrigMito_10
Image_ImageQuality_LocalFocusScore_OrigMito_2
Image_ImageQuality_LocalFocusScore_OrigMito_20
Image_ImageQuality_LocalFocusScore_OrigMito_5
Image_ImageQuality_LocalFocusScore_OrigRNA_10
Image_ImageQuality_LocalFocusScore_OrigRNA_2
Image_ImageQuality_LocalFocusScore_OrigRNA_20
Image_ImageQuality_LocalFocusScore_OrigRNA_5
Image_ImageQuality_MADIntensity_OrigAGP
Image_ImageQuality_MADIntensity_OrigDNA
Image_ImageQuality_MADIntensity_OrigER
Image_ImageQuality_MADIntensity_OrigMito
Image_ImageQuality_MADIntensity_OrigRNA
Image_ImageQuality_MaxIntensity_OrigAGP
Image_ImageQuality_MaxIntensity_OrigDNA
Image_ImageQuality_MaxIntensity_OrigER
Image_ImageQuality_MaxIntensity_OrigMito
Image_ImageQuality_MaxIntensity_OrigRNA
Image_ImageQuality_MeanIntensity_OrigAGP
Image_ImageQuality_MeanIntensity_OrigDNA
Image_ImageQuality_MeanIntensity_OrigER
Image_ImageQuality_MeanIntensity_OrigMito
Image_ImageQuality_MeanIntensity_OrigRNA
Image_ImageQuality_MedianIntensity_OrigAGP
Image_ImageQuality_MedianIntensity_OrigDNA
Image_ImageQuality_MedianIntensity_OrigER
Image_ImageQuality_MedianIntensity_OrigMito
Image_ImageQuality_MedianIntensity_OrigRNA
Image_ImageQuality_MinIntensity_OrigAGP
Image_ImageQuality_MinIntensity_OrigDNA
Image_ImageQuality_MinIntensity_OrigER
Image_ImageQuality_MinIntensity_OrigMito
Image_ImageQuality_MinIntensity_OrigRNA
Image_ImageQuality_PercentMaximal_OrigAGP
Image_ImageQuality_PercentMaximal_OrigDNA
Image_ImageQuality_PercentMaximal_OrigER
Image_ImageQuality_PercentMaximal_OrigMito
Image_ImageQuality_PercentMaximal_OrigRNA
Image_ImageQuality_PercentMinimal_OrigAGP
Image_ImageQuality_PercentMinimal_OrigDNA
Image_ImageQuality_PercentMinimal_OrigER
Image_ImageQuality_PercentMinimal_OrigMito
Image_ImageQuality_PercentMinimal_OrigRNA
Image_ImageQuality_PowerLogLogSlope_OrigAGP
Image_ImageQuality_PowerLogLogSlope_OrigDNA
Image_ImageQuality_PowerLogLogSlope_OrigER
Image_ImageQuality_PowerLogLogSlope_OrigMito
Image_ImageQuality_PowerLogLogSlope_OrigRNA
Image_ImageQuality_Scaling_OrigAGP
Image_ImageQuality_Scaling_OrigDNA
Image_ImageQuality_Scaling_OrigER
Image_ImageQuality_Scaling_OrigMito
Image_ImageQuality_Scaling_OrigRNA
Image_ImageQuality_StdIntensity_OrigAGP
Image_ImageQuality_StdIntensity_OrigDNA
Image_ImageQuality_StdIntensity_OrigER
Image_ImageQuality_StdIntensity_OrigMito
Image_ImageQuality_StdIntensity_OrigRNA
Image_ImageQuality_ThresholdOtsu_OrigDNA_2W
Image_ImageQuality_ThresholdOtsu_OrigRNA_3FW
Image_ImageQuality_TotalArea_OrigAGP
Image_ImageQuality_TotalArea_OrigDNA
Image_ImageQuality_TotalArea_OrigER
Image_ImageQuality_TotalArea_OrigMito
Image_ImageQuality_TotalArea_OrigRNA
Image_ImageQuality_TotalIntensity_OrigAGP
Image_ImageQuality_TotalIntensity_OrigDNA
Image_ImageQuality_TotalIntensity_OrigER
Image_ImageQuality_TotalIntensity_OrigMito
Image_ImageQuality_TotalIntensity_OrigRNA
Image_Scaling_OrigAGP
Image_Scaling_OrigDNA
Image_Scaling_OrigER
Image_Scaling_OrigMito
Image_Scaling_OrigRNA
Image_Series_OrigAGP
Image_Series_OrigDNA
Image_Series_OrigER
Image_Series_OrigMito
Image_Series_OrigRNA
Image_Thumbnail_OrigAGP
Image_Thumbnail_OrigDNA
Image_Thumbnail_OrigER
Image_Thumbnail_OrigMito
Image_Thumbnail_OrigRNA
Image_Width_OrigAGP
Image_Width_OrigDNA
Image_Width_OrigER
Image_Width_OrigMito
Image_Width_OrigRNA

**Comment by jhung0** [comment]
Ok I'll look for alternatives of DBConnect.GetColnamesForClassifier

**Comment by braymp** [comment]
The CPA props file has a <code>classifier_ignore_columns</code> field which can exclude colnames with a regexp. ExportToDB writes it out with some placeholders, but we could put in actual regexps e.g., <code>Image_Width</code>, <code>.Image_Height</code>,<code>Image_Thumbnail</code>, <code>Image_Scaling</code>,<code>Image_Series</code>,<code>Image_Frame</code> if doing image classification per #1771. For object-based classification, I'm not sure you'd want to rule out any thing. In either case, if it's not good, then the user can change the regexps.

**Comment by LeeKamentsky** [comment]
I think that DBConnect.GetColnamesForClassifier is the place to make the change. I'd do it here:
https://github.com/CellProfiler/CellProfiler-Analyst/blob/298648a2e35c774cdd7b4f31427d67b1b33226b6/cpa/dbconnect.py#L1067

just change `type != str` to `type not in str, blob` (and I have no idea what "blob" is). 

I just checked, the classifier is expecting the thumbnails to be in the feature vector, so filtering won't work from my end.

**Comment by jhung0** [comment]
Even then it won't take into account the ignored columns. Also, I don't know how to get it to recognize blob as a type.

**Comment by LeeKamentsky** [comment]
I can probably figure out what type a blob is if you want me to. I was just being lazy and hoping you would do it. Regarding ignored columns, I would pass whatever info you needed to ignore them into DBConnect.GetColnamesForClassifier so you'd be guaranteed that all callers got a consistent answer.

**Comment by braymp** [comment]
Re: ignored cols - The info is already passed: https://github.com/CellProfiler/CellProfiler-Analyst/blob/master/cpa/dbconnect.py#L1082

**Comment by jhung0** [comment]
Oh ok I'll look for the blob type

**Comment by LeeKamentsky** [comment]
Nice catch Mark. I have a feeling that the blob type is None. dbconnect.sqltype_to_pythontype doesn't handle blob although it does handle CLOB.

**Comment by LeeKamentsky** [comment]
The text handled by sqltype_to_pythontype is probably "longblob" (that's what's listed for thumbnail columns in the database) and that is not handled by sqltype_to_pythontype. The if/else logic would cause the function to go straight to the end w/o hitting a return statement and should return None as the type.

**Comment by jhung0** [comment]
For some reason my example is showing all None type columns, so I'll need to take a look

**Comment by LeeKamentsky** [comment]
:rofl: they are all thumbnails! Thanks Jane.

**Comment by braymp** [comment]
If it helps, I can just put the ignore cols in place in the props file and
re-generate the classifier...

**Comment by LeeKamentsky** [comment]
I'm pretty sure you could test my code after doing that. Can you put
Image_x_loc and Image_y_loc in there too?

**Comment by braymp** [comment]
Revised classifier excluding cols: [is_saturated.model.txt](https://github.com/CellProfiler/CellProfiler-Analyst/files/125542/is_saturated.model.txt)
The following cols are excluded (according to the logs): 
```
Ignoring columns: ['ObjectNumber', 'Image_x_loc', 'Image_y_loc', 'ImageNumber', 'Image_FileName_OrigAGP', 'Image_FileName_OrigDNA', 'Image_FileName_OrigER', 'Image_FileName_OrigMito', 'Image_FileName_OrigRNA', 'Image_Frame_OrigAGP', 'Image_Frame_OrigDNA', 'Image_Frame_OrigER', 'Image_Frame_OrigMito', 'Image_Frame_OrigRNA', 'Image_Height_OrigAGP', 'Image_Height_OrigDNA', 'Image_Height_OrigER', 'Image_Height_OrigMito', 'Image_Height_OrigRNA', 'Image_MD5Digest_OrigAGP', 'Image_MD5Digest_OrigDNA', 'Image_MD5Digest_OrigER', 'Image_MD5Digest_OrigMito', 'Image_MD5Digest_OrigRNA', 'Image_Metadata_ChannelNumber', 'Image_Metadata_Date', 'Image_Metadata_FileLocation', 'Image_Metadata_Frame', 'Image_Metadata_Plate', 'Image_Metadata_Series', 'Image_Metadata_Site', 'Image_Metadata_UserStem', 'Image_Metadata_Well', 'Image_PathName_OrigAGP', 'Image_PathName_OrigDNA', 'Image_PathName_OrigER', 'Image_PathName_OrigMito', 'Image_PathName_OrigRNA', 'Image_Scaling_OrigAGP', 'Image_Scaling_OrigDNA', 'Image_Scaling_OrigER', 'Image_Scaling_OrigMito', 'Image_Scaling_OrigRNA', 'Image_Series_OrigAGP', 'Image_Series_OrigDNA', 'Image_Series_OrigER', 'Image_Series_OrigMito', 'Image_Series_OrigRNA', 'Image_Thumbnail_OrigAGP', 'Image_Thumbnail_OrigDNA', 'Image_Thumbnail_OrigER', 'Image_Thumbnail_OrigMito', 'Image_Thumbnail_OrigRNA', 'Image_URL_OrigAGP', 'Image_URL_OrigDNA', 'Image_URL_OrigER', 'Image_URL_OrigMito', 'Image_URL_OrigRNA', 'Image_Width_OrigAGP', 'Image_Width_OrigDNA', 'Image_Width_OrigER', 'Image_Width_OrigMito', 'Image_Width_OrigRNA']
```

**Comment by daviddao** [comment]
I always felt uncomfortable that the user has to know which columns he wants to ignore during the classification process. For example is ObjectNumber probably never a good feature and should be ignored.

However, I am not sure, if its possible to automate feature selection at all each classifier. That is why I implemented a variance check ("Check features" Option).

**Comment by jhung0** [comment]
@LeeKamentsky @braymp  can you try now?

**Comment by jhung0** [comment]
I'm unsure if 
self.classifierColNames = [col for col, type in zip(col_names, col_types) if type not in [str, None]]
is the right thing to do or if it makes the number of columns different than the number of features

**Comment by LeeKamentsky** [comment]
@daviddao This is a little long-term, but the Cytominer project is eventually going to percolate its way down into CellProfiler and it will result in a richer description of each measurement. So you all should keep in mind how you'd like to annotate features in order to mark them as being good candidates for a classifier.
@jhung0 The trick would be to get the code that fetches the feature values to use the same columns, in the same order as the list that's pickled into the classifier. If you use different code paths to get the sequence of columns, there's too much chance of the code diverging and not being correct. The alternate approach would be to get the column names from the description available from the cursor (e.g. cursor.description). This is super rock solid because it is the thing itself.

**Comment by jhung0** [comment]
Ok I guess it does that already. 
https://github.com/CellProfiler/CellProfiler-Analyst/blob/master/cpa/trainingset.py#L325

**Comment by LeeKamentsky** [comment]
How about picking the list like this:

   gimme_pickled_features = [training_set.colnames[i] for i in training_set.col_indices]

That makes sure that the col_indices that are used to order the features for the SQL statement are the same indices that are used to order the features.

**Comment by jhung0** [comment]
I'm pretty sure it does that already because the order the data is presented depends on the order of the features

**Comment by daviddao** [comment]
@jhung0 @LeeKamentsky is this fixed?

**Comment by LeeKamentsky** [comment]
I thought it was. Mark was able to use the feature.

**Comment by daviddao** [comment]
@LeeKamentsky Thanks :), closing it.
