### ISSUE TITLE
Error if saving Classifier model with FGB

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler-Analyst#166]
Creating a classifier model when training with Fast Gentle Boosting yields the following error:
```
An error occurred in the program:
AttributeError: 'FastGentleBoosting' object has no attribute '_set_features'

Traceback (most recent call last):
  File "C:\Trunk\cellProfiler-analyst\cpa\classifier.py", line 1079, in SaveModel
    self.algorithm._set_features(self.trainingSet.colnames)
```
My understanding is that this is probably not fixable since FGB is not in scikit-learn, right? If so, have CPA pop up a wx.MessageDialog gently alerting the user FBG is not supported.

**Comment by daviddao** [comment]
Should be fixed with c18f1061b4e6f6ff0147bd8103a5603bc5ed371b , problem was that the _set_features function was just implemented for GeneralClassifier and not for FGB. Its independent from scikit-learn, because it just stores the TrainingSet Labels
