### ISSUE TITLE
Classifier: Incorporate ImageGallery full-image loading

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler-Analyst#169]
OK, I give up. I've tried to get Classifier to show full-image thumbnails for image classification, but I can't get it to work consistently. Sometimes tile show up tiny, right next to ones that are large.

Is it straightforward to incorporate the image tile loading functionality from ImageGallery (the upper panel) into Classifier for image classification?

**Comment by daviddao** [comment]
Oh yes it should be. I implemented a small flag called display_whole_image. Code example: https://github.com/CellProfiler/CellProfiler-Analyst/blob/852c2e07b7445286dd5291c1c1ed518e9408fe1a/cpa/imagegallery.py#L483 - I think if we replace set the flag to True in classifier.py for image classification, the problem should be solved.

**Comment by daviddao** [comment]
Oh, I see you tried to incorporate those changes with 9bf5fc6f6975e51c80d76d821da28b6852f040b3. Can you send me some image numbers and a properties file where image thumbnails are not working correctly?

**Comment by braymp** [comment]
Try these two (a props file and training set).
[saturated_final_training_set.txt](https://github.com/CellProfiler/CellProfiler-Analyst/files/148474/saturated_final_training_set.txt)
[CDP2_qc_Master.properties.txt](https://github.com/CellProfiler/CellProfiler-Analyst/files/148476/CDP2_qc_Master.properties.txt)

**Comment by daviddao** [comment]
Couldn't reproduce on Mac. Either windows issue or maybe solved?

**Comment by braymp** [comment]
Didn't occur on my VM. When I noticed it, I was on my big screen monitor, so could be related to that? Anyway, I'll close it.
