### ISSUE TITLE
CPA compiled 11710 error dialog upon program exit

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler-Analyst#17]
Simply launching the latest compiled CPA (11710; Windows 7), choosing a properties file, then quitting normally (File->Exit) generates this error message:
http://cl.ly/2S1O3D0P2J3P3P0U3b09

This does not seem to hamper usage of CPA, but might disconcert users.

**Comment by daviddao** [comment]
Haven't seen this issue anymore.
