### ISSUE TITLE
Odd menu bar CPA icon

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler-Analyst#172]
CPA appears in the menu bar at the top of my Mac screen:

![image](https://cloud.githubusercontent.com/assets/1225595/13534539/a7ab7b50-e203-11e5-88fc-842b87f39ffe.png)
and then when quit, it disappears.  It does not respond to clicking and I think it should be removed.  Note that this _menu bar_ icon is in addition to the expected _dock_ icon.

Related to #170 oddity?

**Comment by dlogan** [comment]
P.S. I'm running a recent nightly build on OS 10.10

**Comment by daviddao** [comment]
Just investigated a little bit. We have this odd menu bar icon already in the old CPAnalyst 2.0. Still I also agree that we should remove it.

**Comment by jhung0** [comment]
fixed 20dd845
