### ISSUE TITLE
Filter window too small in windows 10

### ISSUE THREAD

**Issue by jhung0** [CellProfiler/CellProfiler-Analyst#173]
![image](https://cloud.githubusercontent.com/assets/9591682/14007048/59bd3596-f149-11e5-894e-a67c1ecdc026.png)

This is going to Plate Viewer -> Create new filter

**Comment by dlogan** [comment]
Same as #157? Or maybe I just don't understand "This is going to Plate Viewer -> Create new filter"

**Comment by daviddao** [comment]
Thanks @dlogan! Close because of duplicate #157 .
