### ISSUE TITLE
Plate Viewer options gray in Windows 10

### ISSUE THREAD

**Issue by jhung0** [CellProfiler/CellProfiler-Analyst#174]
![image](https://cloud.githubusercontent.com/assets/9591682/14007107/e8ad6bfe-f149-11e5-9a47-b2a3fe856271.png)

**Comment by daviddao** [comment]
Also the buttons look a little bit wrong. I will fix it.

**Comment by daviddao** [comment]
@jhung0 can you check?

**Comment by jhung0** [comment]
yes looks good

**Comment by braymp** [comment]
Not so on my Windows 7 machine, post-commit:
![image](https://cloud.githubusercontent.com/assets/1186440/14078096/bd708a46-f4c0-11e5-8924-36ad3eab4275.png)

**Comment by jhung0** [comment]
Wait what's the problem with that @braymp ?

**Comment by braymp** [comment]
Oh, I'm sorry; I thought he problem was that the some elements are white whereas others are gray. I should have re-read the issue title....

**Comment by daviddao** [comment]
@braymp Thanks for double-checking though! If you want I actually make every element white if you think it is prettier! It's done in a second :)

**Comment by braymp** [comment]
I'm generally for making all the tools consistent in presentation. For example, it seems odd that the drop-downs in e.g. ScatterPlot or Classifier look raised/beveled vs. in PlateViewer. But those are minor issues; if it takes too much time, then no worries....
