### ISSUE TITLE
Periodic "Autosaving failed" msg

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler-Analyst#175]
Running 2.2.1 and loading the cpa_example training set. After a while, I get a notice that autosaving failed:
![image](https://cloud.githubusercontent.com/assets/1186440/14046952/ff4c29c2-f27a-11e5-8f2a-cb30092ddc64.png)
There's no further logging and no apparent negative effect, so I'm not sure what's trying to do and/or where it's failing.

**Comment by daviddao** [comment]
Thanks for reporting! That's happening because after closing the classifier, I don't close the autosave thread. I will fix this in the next commit :)
