### ISSUE TITLE
CPA out of memory ! 

### ISSUE THREAD

**Issue by beghin** [CellProfiler/CellProfiler-Analyst#177]
Dear CPA developer,

I have already contacted you one year ago : i am Anne BEGHIN, i daily work  with CPA to manage data from super resolution (SR) images. As SR images could have a lot of objects to manage, I generate easily data base with more than million of objects in tens wells. And it seems  it doesn't work if a .CSV have more than 1 million of object approx....

Hope to find some helps here ! 

Cheers
Anne

P.S : And also we continue to have some fundings to work on this project, but for now this is the last year and we are very interesting to find more fundings. For that we are searching for collaborators...maybe we can discuss for that on another place ?

**Comment by daviddao** [comment]
Hi Anne,

Nice to meet you! Which version of CPA are you using? 

Best,
David

**Comment by beghin** [comment]
Dear David, 

Nice to meet you too ! 
I'm using CPA 2.0 (r11710). I have to precise that it seems to be due to a database out of memory as it crashs when I try to open a new table to incorporate it at the existing database (so i'have got several tables, not only per_image and per_object). 

Cheers 
@nne 

Anne Beghin, PhD 
Institut interdisciplinaire de Neurosciences 
CNRS UMR 5297-Bât PGF 
Université Bordeaux 2 
146 rue Léo Saignat 
33077 Bordeaux cédex 
Tél : 05 57 57 56 74 


De: "David Dao" <notifications@github.com> 
À: "CellProfiler/CellProfiler-Analyst" <CellProfiler-Analyst@noreply.github.com> 
Cc: "beghin" <anne.beghin@u-bordeaux.fr> 
Envoyé: Mercredi 13 Avril 2016 22:08:42 
Objet: Re: [CellProfiler/CellProfiler-Analyst] CPA out of memory ! (#177) 



Hi Anne, 

Nice to meet you! Which version of CPA are you using? 

Best, 
David

**Comment by jhung0** [comment]
Hi Anne,
Could you try using the new version found here: https://github.com/CellProfiler/CellProfiler-Analyst
Let us know if the same problem occurs.

**Comment by beghin** [comment]
Dear Jane, 

I am sorry but the installer of the new version does not seem to work : impossible to launch the .exe. I have dowloaded the JDK and my OS is windows 7 : jdk-8u91-windows-x64.exe. 
(I am "administator" of my PC, so this is not a problem of authorization to write/modify something..." 

Any idea ? 

Cheers 
@nne 

Anne Beghin, PhD 
Institut interdisciplinaire de Neurosciences 
CNRS UMR 5297-Bât PGF 
Université Bordeaux 2 
146 rue Léo Saignat 
33077 Bordeaux cédex 
Tél : 05 57 57 56 74 


De: "Jane Hung" <notifications@github.com> 
À: "CellProfiler/CellProfiler-Analyst" <CellProfiler-Analyst@noreply.github.com> 
Cc: "beghin" <anne.beghin@u-bordeaux.fr> 
Envoyé: Jeudi 14 Avril 2016 16:25:59 
Objet: Re: [CellProfiler/CellProfiler-Analyst] CPA out of memory ! (#177) 



Hi Anne, 
Could you try using the new version found here: https://github.com/CellProfiler/CellProfiler-Analyst 
Let us know if the same problem occurs.

**Comment by daviddao** [comment]
Try out the nightly build here: http://d1zymp9ayga15t.cloudfront.net/CellProfiler-Analyst-nightly.exe Thanks so much :)

**Comment by beghin** [comment]
Dear Jane, 

I seems to work now...quite slow but it load everything. 

Just for info : it seems that Avast blocks the launcher of your installer...As soon as I remove Avast the installer launch perfectly. A colleague have tried with Avira and no problem with this Antivirus. 

So you still develop CPA now ? 

Cheers 
@nne 

Anne Beghin, PhD 
Institut interdisciplinaire de Neurosciences 
CNRS UMR 5297-Bât PGF 
Université Bordeaux 2 
146 rue Léo Saignat 
33077 Bordeaux cédex 
Tél : 05 57 57 56 74 


De: "Jane Hung" <notifications@github.com> 
À: "CellProfiler/CellProfiler-Analyst" <CellProfiler-Analyst@noreply.github.com> 
Cc: "beghin" <anne.beghin@u-bordeaux.fr> 
Envoyé: Jeudi 14 Avril 2016 16:25:59 
Objet: Re: [CellProfiler/CellProfiler-Analyst] CPA out of memory ! (#177) 



Hi Anne, 
Could you try using the new version found here: https://github.com/CellProfiler/CellProfiler-Analyst 
Let us know if the same problem occurs.

**Comment by daviddao** [comment]
Thanks for the information! We are glad it is working. @jhung0 and I are the current developers of CPA. Please feel free to contact us at anytime!
