### ISSUE TITLE
Save thumbnail as JPEG issue in classifier.py

### ISSUE THREAD

**Issue by abbasjariani** [CellProfiler/CellProfiler-Analyst#179]
Hi,

When saving the thumbnails of training samples, they are saved with jpeg extension however the format saved is actually png. This causes confusion and error when opening the saved thumbnails.

Abbas

in classifer.py:
                    imagetools.SaveBitmap(tile.bitmap, directory + '/training_set/' + str(label) + '/' + str(tile.obKey) + '.jpg')

**Comment by daviddao** [comment]
Thanks for reporting! I will change that for the next nightly build! 
PS: Also awesome that you discovered the function and are using it!
