### ISSUE TITLE
Box plot big problem.

### ISSUE THREAD

**Issue by beghin** [CellProfiler/CellProfiler-Analyst#181]
Dear CPA developers,

I have already mentioned that but maybe now you have got a solution : I would like to compare in the same boxplot different wells for the same feature. In X of a boxplot, I would like to group data by well (and not by measurement) and display one graph with all boxplot per well for one measurement in Y. Do you have a solution for that ? Even if it is a SQLQuery...
If not, that means users need to have another software to represent data in a "statistic" mode and so to export data, right ? 

Thanks a lot !
Anne

**Comment by jhung0** [comment]
I don't think you can currently do that with boxplot, but if you go to the
Advanced menu option of the main window, you can choose Launch SQL query
tool and get the data you want that way.

**Comment by beghin** [comment]
Dear CPA developers, 

Another question : is it possible to save graphs in a vectorial format (.SVG for example) ? 

Many thanks again. 

@nne 

Anne Beghin, PhD 
Institut interdisciplinaire de Neurosciences 
CNRS UMR 5297-Bât PGF 
Université Bordeaux 2 
146 rue Léo Saignat 
33077 Bordeaux cédex 
Tél : 05 57 57 56 74 


De: "Jane Hung" <notifications@github.com> 
À: "CellProfiler/CellProfiler-Analyst" <CellProfiler-Analyst@noreply.github.com> 
Cc: "beghin" <anne.beghin@u-bordeaux.fr>, "Author" <author@noreply.github.com> 
Envoyé: Mercredi 18 Mai 2016 12:52:02 
Objet: Re: [CellProfiler/CellProfiler-Analyst] Box plot big problem. (#181) 

I don't think you can currently do that with boxplot, but if you go to the 
Advanced menu option of the main window, you can choose Launch SQL query 
tool and get the data you want that way.

**Comment by jhung0** [comment]
No, it isn't currently supported, but feel free to make an issue on Github
if you'd like to see that as a feature.
