### ISSUE TITLE
Enable selecting measurements to view in TableViewer 

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler-Analyst#186]
This is useful, for example, if I want to just take a quick look at the raw image measurements (for a particular measurement, perhaps for a particular image). This could be per_object or per_image data.

Probably would be helpful to warn the user "The table you have specified has 100,000 rows, would you like to just view 100 rows?" (with the latter being editable.... we have a similar dialog box when the user chooses a very large number of cells to view in the ImageGallery so perhaps copy that wording). Same for tables with an unreasonable number of columns.

**Comment by jhung0** [comment]
@daviddao  didn't you have some code where you could select the columns?

**Comment by daviddao** [comment]
Yes, using table viewer it is possible to show and hide columns. 
For rows, we can only do it manually currently using an SQL command in **Advanced->Launch SQL query tool**

![screen shot 2016-06-15 at 12 54 41](https://cloud.githubusercontent.com/assets/1241240/16077311/62360a5e-32f8-11e6-89a0-b110887e14f8.png)

**Comment by AnneCarpenter** [comment]
I see, the functionality exists! Closing.
