### ISSUE TITLE
Images and/or measurements are upside down

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler-Analyst#188]
In CPA 2.2.1  
To reproduce:

Open CPA and load a properties file.
Open Scatterplot tool
Choose x axis as per_object Nuclei_Location_CenterX
Choose y axis as per_object Nuclei_Location_CenterY
apply a filter for a single image (so we only see data from cells from one single image)
Click Update Chart to create the scatterplot

Separately, choose the Image Gallery tool and select the same image to view. 
Once it displays, double click it to open in a large window.

Notice that either the measurements or the image are flipped relative to each other (top is bottom, bottom is top).

Not sure whether this is a problem in how CP is storing the locations or in how CPA is displaying the  XY locations and/or the image.

Here is how it looks:
![upsidedown](https://cloud.githubusercontent.com/assets/1213811/15987055/37024940-2fd0-11e6-9b3f-45ef10c7310a.jpg)

**Comment by jhung0** [comment]
Probably in CP the 0,0 point is in the top left corner while here 0,0 is in the bottom left corner.

**Comment by jhung0** [comment]
Is it worth changing the axes of the scatter plot to match CP?

**Comment by AnneCarpenter** [comment]
I recommend seeing how the same image appears within CellProfiler and matching that. Either flipping the image or the axes.

**Comment by AnneCarpenter** [comment]
Oh.... Wait. I see. This is not actually an error how the scatter plot is displayed. I think the image likely looks like it would be displayed in CellProfiler. The scatter plot looks upside down but only because that's how the axes are drawn. 

Ok, so, no, it does NOT make sense to flip the axes because most measurements you do want zero, zero in the bottom left. This is just a very peculiar case where that's confusing but I don't see any way to make it less confusing. So we can close this issue as "user error"!
