### ISSUE TITLE
Improve gentle boosting performance

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler-Analyst#19]
A user reports that CPA's multiclass GB takes much longer to run than a similar implementation in MATLAB (3-4 minutes for 50 rules, 21 secs in MATLAB)

MATLAB's implementation: http://www.mathworks.com/matlabcentral/fileexchange/22997

-------------------------------------------------------
From Ray:
Looking deeper, I think it's just that our code is not as optimized.  It does a lot of unnecessary work in the setup in fastgentleboosting.TrainWeakLearner() that could be cached, instead.

-------------------------------------------------------
From Ray again:
It's possible the two algorithms extend GB to the multiclass case in different ways.  I should look at what the matlab version does.  It might be that my implementation is broken, but not broken enough for us to have noticed.

The matlab version has several optimizations we haven't implemented.  The most obvious is probably sorting all the features once at the beginning.  Our implementation sorts every feature in every iteration of the algorithm.  That could easily account for most of the slowdown.

-------------------------------------------------------
Sample training set + performance graph at http://www.broadinstitute.org/~mbray/ForCPAperformance.zip

**Comment by AnneCarpenter** [comment]
We now have multiple options for classifiers. Probably not worth the effort to improve speed.
