### ISSUE TITLE
The confusion matrices calculated in CPA don’t seem to be correct (for imbalanced data sets) [critical]

### ISSUE THREAD

**Issue by holgerhennig** [CellProfiler/CellProfiler-Analyst#191]
Classifier window, evaluate button.
The confusion matrices calculated in CPA don’t seem to be correct. Some classes have 0% true positive rate.
Example db and properties file:
https://www.dropbox.com/s/miz9jya3ywz300m/CellCycleJurkat_org.db?dl=0
https://www.dropbox.com/s/n4gwl53r6yhbvbc/CellCycleJurkat_MyExpt.properties?dl=0

The example db is a highly imbalanced data set (over 30,000 cells in class G1/S/G2 and 15 cells in class Anaphase). I guess what might have happened is that during 5-fold cross validation randomly 80% of the cells in the training set are selected (hence the chance to randomly include an Anaphase cell in the training set is almost zero. That would explain 0% true positive rate), but it is important to select 80% of cells in each class! In addition, for such a highly imbalanced data set, 10-fold cross validation would perform better because the test sets are larger (if you only have 15 cells in one class that is likely to make a difference). As 10-fold cv is also a standard choice, I recommend 10-fold cv.

Recommended fix: Select 90% of the cells in each class, and cross-valide (10-fold). I hope that'll fix the issue
Example: if the user places 10 cells in class A, then 9 cells from class A should be in each of the training sets for cross-validation.

**Comment by jhung0** [comment]
Strange, the classifier is stratified already. Which classifier are you using?

**Comment by jhung0** [comment]
@daviddao what about letting the user choose the # of folds? Would it be easy?

**Comment by jhung0** [comment]
Letting user choose # of folds for Evaluate... done in 6c4798a

**Comment by holgerhennig** [comment]
Hmm, bummer, I was kinda hoping sampling wasn't stratified yet, because stratifying would then fix the issue. I have used GradientBoosting and RandomForests. 

Thanks for implementing letting the user choose # of folds for Evaluate!

Let's see what 10-fold cross-validation (or even 20-fold cv) gives, for such highly imbalanced data sets with very low cell counts in some classes it can make quite a difference whether 80% or 90% of the cells (per class) are in the training set..

**Comment by holgerhennig** [comment]
Test result: the cross-validation results in CPA seem to be consistent (tested for GradientBoosting and RandomForests), issue can be closed from my point of view. Thanks!
