### ISSUE TITLE
Fetch n cells from Experiment (or from any filter) contains duplicate cells [critical for usability]

### ISSUE THREAD

**Issue by holgerhennig** [CellProfiler/CellProfiler-Analyst#193]
Navigate to: Classifier window. Fetching n cells from Experiment (or from any filter created by the user) contains duplicate cells. 

Recommended fix: The set of n fetched cells should not contain duplicate objects. Draw n unique values from the integers 1:m, for n<=m. 
Example: Python code to draw n=100 unique cells from an image with m=225 cells looks something like this:
np.random.choice(225, 100, replace=False)

Further info: We need to fetch 100 objects from an image with 225 objects. So far I need to manually drag&drop each object (100 times!) for a single class to make sure there are no duplicates.

**Comment by braymp** [comment]
See https://github.com/CellProfiler/CellProfiler-Analyst/issues/81 for more info.

**Comment by jhung0** [comment]
@holgerhennig  so you just care that the images you get when you fetch once are distinct and not that separate fetches might give you the same cell multiple times?

**Comment by holgerhennig** [comment]
@jhung0 Yes, exactly, I suggest that the images you get when you fetch once are distinct. Thus, when you fetch images several times then there can be the same image multiple times. 

The advantages are (i) one can immediately create a distinct set of n images. That's essential for creating a good training set for highly imbalanced data sets. (ii) if needed, the user can easily have images occuring multiple times by fetching several random sets of images (each image set is distinct, but not the joined sets)

**Comment by jhung0** [comment]
Ok I think it should be there with 1bb77ab

**Comment by holgerhennig** [comment]
Test result: Didn't work in our data set. I fetched 15 random cells from anaphase (which is image 1 and contains 15 cells in total). There are several duplicate cells among the 15 random cells, screenshot attached. I suppose this is a general issue not specific to our data, did you check it in one of your data sets? Thanks!
<img width="965" alt="fetch_n_distinct_cells_bug" src="https://cloud.githubusercontent.com/assets/5438649/16376044/c66ee9fe-3c5e-11e6-8133-03435819215f.png">

**Comment by AnneCarpenter** [comment]
Once this actually is fixed, be sure the documentation is also updated, to avoid confusion.

**Comment by jhung0** [comment]
Tried to fix so see if it works

**Comment by holgerhennig** [comment]
test result: works great. However, when an image has n objects, then only n-1 random objects can be fetched. Pls allow fetching all n distinct objects.
Below is the error msg when attempting to fetch 15 out of 15 cells (fetching 14 out of 15 cells works fine).

An error occurred in the program:
ValueError: sample larger than population
Traceback (most recent call last):
  File "/Applications/CellProfiler Analyst_nightly.app/Contents/Resources/lib/python2.7/cpa/classifier.py", line 910, in OnFetch
    obKeys = dm.GetRandomObjects(nObjects, filteredImKeys)
  File "/Applications/CellProfiler Analyst_nightly.app/Contents/Resources/lib/python2.7/cpa/datamodel.py", line 132, in GetRandomObjects
    obIdxs = random.sample(range(1, sums[-1]), N)#randint(1, sums[-1])
  File "random.pyc", line 323, in sample

**Comment by jhung0** [comment]
Should be fixed with 5b0aa8d

**Comment by holgerhennig** [comment]
tested. works great, thx! Issue can be closed
