### ISSUE TITLE
delete class -> CPA terminates

### ISSUE THREAD

**Issue by holgerhennig** [CellProfiler/CellProfiler-Analyst#194]
Navigate to: Classifier window. Right-click a bin and select: delete class -> CPA terminates

**Comment by jhung0** [comment]
I can't replicate

**Comment by daviddao** [comment]
I can replicate but only with delay. Strange.

**Comment by daviddao** [comment]
@jhung0: Same as https://github.com/CellProfiler/CellProfiler-Analyst/issues/195#issuecomment-226356619. It only happens in the app. Heisenbug returns.
