### ISSUE TITLE
Right-click on an image and select delete ->  CPA terminates

### ISSUE THREAD

**Issue by holgerhennig** [CellProfiler/CellProfiler-Analyst#195]
Navigate to: Classifier window. Right-click on an image and select delete ->  CPA terminates.
Workaround: Selecting on or more images and hitting delete key works fine

**Comment by jhung0** [comment]
Can't replicate this

**Comment by AnneCarpenter** [comment]
I can. I'm using 2.2.1 per the About window. What I did:
- Launch CPA
- load properties file (I'm using the example DB and images from our site)
- click Classifier
- Choose "no" to load existing training set
- fetch 20 random cells from experiment
- click the first cell (top left)
- right click it and "remove selected"
- there is a slight pause, then CPA crashes.

Log file attached
[2016_06_15_logfile.txt](https://github.com/CellProfiler/CellProfiler-Analyst/files/316860/2016_06_15_logfile.txt)

**Comment by jhung0** [comment]
Ok it happens in the app but not the developer version

**Comment by jhung0** [comment]
@daviddao  any idea why?

**Comment by bethac07** [comment]
Just had a couple people get bit by this in the workshop- they were all running the Mac stable FWIW.

**Comment by jhung0** [comment]
I guess our first step would be to figure out how to build CPA again...

**Comment by daviddao** [comment]
Agreed. I have no access to the build machine. My last update (and hope) was that we have automatic builds. Maybe we just have to restart Jenkins (in our collaborator room).

**Comment by minh-doan** [comment]
This issue came up to many workshop attendants recently.

**Comment by jhung0** [comment]
If nobody knows what to do, I can remove the delete option?

**Comment by jhung0** [comment]
As I said, it doesn't show up in the developer version, so I have 0 idea what's going on.
