### ISSUE TITLE
An IOError can appear when clicking on "Evaluate" (even if it worked earlier)

### ISSUE THREAD

**Issue by holgerhennig** [CellProfiler/CellProfiler-Analyst#196]
Navigate to classifier window, create test set. After having used several classifiers, the following error can appear when clicking on "Evaluate" (even if it worked earlier):
Error msg: "An error occurred in the program:
IOError: [Errno 32] Broken pipe"

After that error has occurred once, "Evaluate" stops working for all classifiers (producing the error above). This bug seems difficult to reproduce. Low priority.
Workaround: Save training set and reload CPA.

**Comment by bfeng0** [comment]
I am having this problem a lot.  I have no trouble reproducing it.  If there are easy things to upload to help diagnose the bug I'd be happy to try and upload them.  I'm not sure how useful my SQLite db file or properties file would be for this.

**Comment by jhung0** [comment]
@daviddao ideas?

**Comment by bethac07** [comment]
Replicated it again in yesterday's nightly.

**Comment by daviddao** [comment]
I will take a look and get into touch as soon as I know more

**Comment by DavidStirling** [comment]
Haven't ever encountered this, evaluate has been reworked. Feel free to re-open if it's found again in 3.0
