### ISSUE TITLE
Feature request: data cleaning. Add switch to properties file to normalize features

### ISSUE THREAD

**Issue by holgerhennig** [CellProfiler/CellProfiler-Analyst#198]
"normalize = yes" (set default value to yes) 
Further info: normalize all features (like Matlab's zscore function), i.e. each feature is centered to have mean 0 and scaled to have standard deviation 1.

**Comment by AnneCarpenter** [comment]
There are a number of methods to normalize. Would you have this happen on startup? Should it create a new table in the database? If so, the next time the user starts up will the normalization happen from scratch again, to create a new table, or will it know to access the previously-created table? 

This is likely a relatively complex effort and overlapping with cytominr work, so I propose we mark as future consideration. As with #199 we would want to consider where the dividing line is between cytominr and CPA: that is, how much pre-processing should CPA offer vs requiring it be done outside? And if it is done inside CPA should it be a switch in the properties file, or instead a menu item that is explicitly performed?

BTW, @holgerhennig did you know there is a normalization tool in CPA? From the main menu, Tools > Normalization Tool?  It's a bit buggy, however.

**Comment by holgerhennig** [comment]
I didn't know there was a normalization tool, that's handy (and may be more user friendly than having users edit the prop file). Then a switch in the prop file is not needed. One could consider adding the functionality "excluding zero variance features" (issue #199) to the tool, and debug the normalization tool if necessary.

**Comment by AnneCarpenter** [comment]
I've created an issue to add the Normalization Tool to the main toolbar (#228) so it's not easily overlooked.
