### ISSUE TITLE
Feature request: provide pdf of sphinx manual in addition to html version

### ISSUE THREAD

**Issue by holgerhennig** [CellProfiler/CellProfiler-Analyst#202]
main motivation: text search in current sphinx html manual only finds exact matches.
example-
search for: feature
will not find: features

**Comment by daviddao** [comment]
Hi Holger, 
That is very easy. 
You can just go to the `docs` folder in CPA and type `make latexpdf`. 
Inside the `build` folder you will now get a new pdf file.

I added the resulting pdf here for your convenience:
[CPAdocs.pdf](https://github.com/CellProfiler/CellProfiler-Analyst/files/338211/CPAdocs.pdf)
