### ISSUE TITLE
Feature request: Add RUS boosting

### ISSUE THREAD

**Issue by holgerhennig** [CellProfiler/CellProfiler-Analyst#204]
Add random undersampling (RUS) boosting. Would be great to have it for analyzing highly imbalanced data sets. If scikit-learn contains another algorithm that uses random undersampling that might work too. Not urgent

**Comment by AnneCarpenter** [comment]
@daviddao and @jhung0 Among the currently available classifiers in CPA, what would you recommend for imbalanced data sets?

**Comment by daviddao** [comment]
That is a very good question because overall accuracy is not a useful metric for imbalanced data (the confusion Matrix is however). I would recommendations to use LDA.

**Comment by AnneCarpenter** [comment]
ok! Closing this, for future consideration. If there is compelling need, we can re-open.
