### ISSUE TITLE
Feature Request- show pixel intensity with mouse hover

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler-Analyst#206]
When you're looking at an image in CellProfiler there's a toolbar on the bottom that displays the intensity in all channels of whatever pixel your mouse is hovering over; this would be helpful to have in CPA for when you're doing QC and need to tell if individual channels are actually saturated or just quite bright.  

Thanks!

**Comment by AnneCarpenter** [comment]
If/when this happens, keep an eye on work for this functionality in CellProfiler:
https://github.com/CellProfiler/CellProfiler/issues/2021
