### ISSUE TITLE
"Error loading classifier model" upon trying to load saved non-FGB model

### ISSUE THREAD

**Issue by bfeng0** [CellProfiler/CellProfiler-Analyst#207]
Hi All-

I have an issue regarding the functionality of saving a classifier model and opening it in a new Analyst session. I am able to do this with the Fast Gentle Boosting model, but none of the others work. The console tells me "Error loading classifier model."  This error appears whether or not I have a training set loaded.  

I've found this to be the case under both CPA 2.2.1 and the nightly build.

Thanks,
Brian

**Comment by jhung0** [comment]
Thanks for catching that. Should be fixed with 598b671

**Comment by bfeng0** [comment]
Tested the nightly build out and indeed it appears that loading models works better, but in attempting to apply them (via score all) to a different dataset I get the following error: "AttributeError: 'NonType' object has no attribute 'labels'"

![screen shot 2016-07-14 at 1 08 27 pm](https://cloud.githubusercontent.com/assets/20427876/16858617/09b25972-49dd-11e6-8500-29dd21520891.png)

I can manage to apply the model to the whole data set if I load the exact training set I used to train the model (RF, in this case) load the model, and then click score all.  But that defeats the purpose of saving the model.

Thanks!

**Comment by jhung0** [comment]
Oh ok. Should be fixed with 8ef08a63ccdbd7aeaf26f8dad7f57ec20f635ae8

**Comment by bfeng0** [comment]
Hi again-  The models can be applied now, thanks! However, I noticed that after loading a model, the "score image" functionality isn't working correctly.  The classes listed in the "show controls" tab are not accurate; they are populated with classes not specified in the model, and checking/unchecking the checkboxes for each label does not affect the classification overlay in the image part of the tab. I attached an image below with an example of all of the classes; my model should only have 5.

Notably, the "score all" functionality and the data table that comes from clicking score image **do** contain the right classes.  Though when using "score image" the data table produced does get the classes mixed up, as previously noted:

https://github.com/CellProfiler/CellProfiler-Analyst/issues/180

![screen shot 2016-07-18 at 12 25 23 pm](https://cloud.githubusercontent.com/assets/20427876/16928847/b6e29a6c-4ce9-11e6-818a-2e134bc249b9.png)

thanks!

**Comment by bfeng0** [comment]
Looks like I spoke too soon about application of the models.  Whereas I am able to save/load/apply models created from a specific database file to the same database file, when I try to apply those models to a different database (of the same structure as the original database), I get the following errors:

The first time I click "score all":
![screen shot 2016-07-18 at 2 57 07 pm](https://cloud.githubusercontent.com/assets/20427876/16931879/0b6ad4f6-4cf8-11e6-9719-2aa3cf38b8fc.png)

The second time I click "score all":
![screen shot 2016-07-18 at 2 57 29 pm](https://cloud.githubusercontent.com/assets/20427876/16931885/14705e5e-4cf8-11e6-9fd7-388b88c39482.png)

**Comment by bfeng0** [comment]
Hm, Ok, that make sense.  However, the labels in the image don't correspond to any of the classes I can check/uncheck.  That is to say, I can uncheck all of the boxes and not see any change in the visibility of the object classes on the screen.

**Comment by jhung0** [comment]
So even if you uncheck all boxes you can still see them on the screen?

**Comment by bfeng0** [comment]
Yes, exactly.

**Comment by jhung0** [comment]
I can't replicate that... maybe try it with the new nightly?

**Comment by bfeng0** [comment]
Tried, and still observed.  

First image: all classes unchecked and class 10 (untreated) objects all remain on the screen.
Second image: Class names getting scrambled on the table (all the objects are in the "round" category when they are correctly being called as "untreated" on the image).

![screen shot 2016-07-22 at 8 51 23 am](https://cloud.githubusercontent.com/assets/20427876/17062940/d8c1d97e-4fe9-11e6-8dce-45eb5c95599d.png)
![screen shot 2016-07-22 at 8 54 20 am](https://cloud.githubusercontent.com/assets/20427876/17062959/e9325702-4fe9-11e6-8cc2-9c28c7c05f15.png)

**Comment by jhung0** [comment]
Can you try with the example.properties file that comes with CPA?

**Comment by bfeng0** [comment]
Sorry for the delay.  I tried this with the example data set and was unable to reproduce the problem.

**Comment by jhung0** [comment]
Ok... don't know what's going on. In any case, could you make a  new issue so I can close this one?
