### ISSUE TITLE
Error if Evaluation> Confusion matrix chosen and classifier = FGB

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler-Analyst#208]
Evaluating a classifier produced with FGB with the output as a confusion matrix produces the error:
```
An error occurred in the program:
TypeError: ConfusionMatrix() takes exactly 1 argument (2 given)

Traceback (most recent call last):
  File "C:\Users\brayma2\Desktop\github\cellprofiler-analyst\cpa\classifier.py", line 1288, in OnEvaluation
    self.algorithm.ConfusionMatrix(folds)
```

**Comment by jhung0** [comment]
@daviddao did you work on that?

**Comment by braymp** [comment]
Yes, with https://github.com/CellProfiler/CellProfiler-Analyst/issues/94

**Comment by daviddao** [comment]
Ok, let me check !

**Comment by daviddao** [comment]
I couldn't reproduce the issue on the example.properties file. Are you working with 2.2.1 or nightly?

![screen shot 2016-07-22 at 14 12 14](https://cloud.githubusercontent.com/assets/1241240/17056839/785653da-5016-11e6-9263-fc4ee13de194.png)

**Comment by braymp** [comment]
I'm working from source. I think you can see [here](https://github.com/CellProfiler/CellProfiler-Analyst/blob/27aacf14e9882845a603544736e9f7541cbea851/cpa/fastgentleboosting.py#L492) that there's no <code>folds</code> argument for FGB.

**Comment by daviddao** [comment]
Ok, got it! Upgrading to folds in 6c4798a breaks the code for FGB. That is why i couldn't reproduce in the stable version. I am on it :) !

**Comment by daviddao** [comment]
Solved with  7a173ba

**Comment by dlogan** [comment]
Question about this: Does this mean that the FGB cross-validation before this last commit actually had only a single fold? Or?  I ask because I tried a CPA nightly from a couple weeks ago and the cross-validation performance of FGB was markedly worse than all the other classifiers.  It didn't error, rather just bad accuracy.  Or is it simply a function of the classifier do you think?

**Comment by jhung0** [comment]
It just meant fgb didn't have an adjustable number of folds. Maybe David
can check again but I think default was 5 folds. Now it's either still that
default or you can choose the number of folds.

**Comment by daviddao** [comment]
FGB always had 5 folds as default. It might be a simple function of the classifier because we are comparing our own version of FGB with optimized algorithms from scikit-learn.
