### ISSUE TITLE
Combine individual _link_tables/_link_columns into single indexed table

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler-Analyst#21]
The _link_tables/_link_columns concept works well but is unsightly in terms of the number of tables that can be created. Some of which may be unused if the originating table name changes.

It would be nice to have just one master _link_tables/_link_columns table that works similar to how the Experiment table operates for each batch run, or the way that the batchprofiler tables are used. Perhaps a single index or hash for each.

**Comment by AnneCarpenter** [comment]
@braymp Is this still an important issue, or "would be nice" (we are closing the latter and marking for future consideration).

**Comment by braymp** [comment]
Def. "would be nice". I'll close/label.
