### ISSUE TITLE
Feature request- specify class names in Classifier in properties file

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler-Analyst#210]
If a user often creates the same classes (and particularly if there are a lot of them), it'd be nice to have an option to edit the properties file so that classes are designated automatically.

**Comment by braymp** [comment]
Do you mean that you'd want a field like this
```
class_names = <phenotypeA>,<phenotypeB>, <phenotypeC>
```
and when you open it in CPA, the 3 (or however many) class bins are already available and named appropriately?

**Comment by bethac07** [comment]
Yes, precisely.  Thank you for clarifying it better than I did! :smile:

**Comment by jhung0** [comment]
Ok try with 96da88e

**Comment by AnneCarpenter** [comment]
@bethac07 Looks like this is awaiting you testing/confirming.

**Comment by bethac07** [comment]
Looks great!  Sorry for letting it slip through the cracks.
