### ISSUE TITLE
Feature request for future- classify via clicking on image rather than bins

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler-Analyst#211]
Instead of or in addition to dragging and dropping to bins the way you do now, it'd be cool if you could just open an image in Classify, have a dropdown/list of checkboxes/something on the side or bottom where you select which class you want to assign, then click around to the different objects on the image.  Next class, click a few more objects, etc, then hit a "done" button.  Long term future but good idea from a collaborator.

**Comment by AnneCarpenter** [comment]
Definitely convenient tool idea. Marking for future consideration.
