### ISSUE TITLE
Feature request- import training set measurements from previous experiments

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler-Analyst#212]
If a user trains Classifier on a given set of images then realizes they don't have sufficient images to get the classification to the point that they'd like it BUT doesn't want to lose the classification they've done so far, to my knowledge there is only one way to do it (below) and it's reasonably hacky.  It'd be nice to be able to load the classes and feature measurements of objects already trained; I understand the thumbnails would be a giant pain (because the TrainingSet.csv files only have relative ImageNumbers in them) but the list of measurements seems like it should be doable.  

------------------------
1) Save your training set
2) Add more images in CP
3) If your images 1-5 from your "original set" aren't 1-5 now in CP's assignment order (likely):
3a) Export the file list as a .txt file
3b) Import the text file into Excel
3c) Split everything into file names and path names
3d) Re-order the list of files 
3e) Save as CSV
3f) Change your pipeline to run LoadData rather than the images modules
4) Run CP again
5) Open CPA and import your training set.

**Comment by jhung0** [comment]
How is it different than save model?

**Comment by bethac07** [comment]
I don't actually know; the .model files are a bit of a black box to me.  If that's basically what model does, I'm a happy camper :).  Sorry!
