### ISSUE TITLE
Improvement of usability: control panel in Score Image

### ISSUE THREAD

**Issue by holgerhennig** [CellProfiler/CellProfiler-Analyst#215]
Current state: list of classes in controls panel doesn't appear to be ordered.
Suggested target state: first list all classes
Classes:
1) A
2) B
3) C 
then, in a new column to the right of the Classes column list all training classes 
Classes (training set):
4) training A 
5) training B
6) training C

Screenshot is current state.
![score_image](https://cloud.githubusercontent.com/assets/5438649/17221503/6060d312-54f4-11e6-902c-fe9e60472478.png)

**Comment by jhung0** [comment]
try with 72d4b79

**Comment by holgerhennig** [comment]
tested & works great, thx! Suggest to close the issue
