### ISSUE TITLE
improvement of usability: headings in Score All and Score Image

### ISSUE THREAD

**Issue by holgerhennig** [CellProfiler/CellProfiler-Analyst#216]
Current state: headings are a single row, text doesn't fit in column width (unless manually adjusting each column width but then the window can become very wide)
Suggested target state: Use two rows for headings, i.e. "training total \newline cell count"  

Screenshot is current state when running "Score All".

![score_all](https://cloud.githubusercontent.com/assets/5438649/17221578/a9b6384a-54f4-11e6-84fd-41187297355f.png)

**Comment by jhung0** [comment]
bcc8b7f

**Comment by holgerhennig** [comment]
tested, looks great, thanks! suggest to close issue
