### ISSUE TITLE
improvement of usability: Score Image - legend with colors (corresponding to colored markers on cells in image)

### ISSUE THREAD

**Issue by holgerhennig** [CellProfiler/CellProfiler-Analyst#217]
Current state: When running "Score Image", cells are marked with colored squares. The legend has no colored labels.
Suggested target state: add square with the same color to class legend (similar to figure legends in publications).
Example: Say, we have defined classes A and B and the cells classified as A are marked with a blue square, and B cells are marked with a red square.
The desired state would be the following legend: 

Classes:
1) A [place blue square here]
2) B [place red square here]

Screenshot is current state (CPA nightly build)
![score_image](https://cloud.githubusercontent.com/assets/5438649/17221676/0b94fac4-54f5-11e6-94c7-a196c33b1de1.png)

**Comment by jhung0** [comment]
fixed along with #215

**Comment by holgerhennig** [comment]
tested, works great, thanks!! Issue can be closed
