### ISSUE TITLE
Image viewer: Classify menu item opens a new image

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler-Analyst#218]
To replicate:
- Load the cpa_example properties file
- Open Classifier, load the default training set, train classifier w/ RandomForest
- Dbl-click any of the image tiles to open the full image.
- Select "Classify" from the menu.

A new image viewer opens with the same full image + classification labels. Proper behavior should be to use the current full image.

**Comment by DavidStirling** [comment]
This turned out to be a bit tricky, so instead it now closes the original and floats the new window to the top.
