### ISSUE TITLE
Compiled CPA: If initial properties dialog canceled, splash screen remains visible + cpa.exe stays in memory

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler-Analyst#22]
This issue occurs on Windows machines; have not confirmed for Macs.

**Comment by daviddao** [comment]
I checked it on Windows Vista for the new version of the master branch d6e97798d123c1be2a103e03e0e070f705876d71 (running from source) and couldn't reproduce this issue. I think it could be solved with #102 . Feel free to reopen at any time.
