### ISSUE TITLE
Release version of CPA hangs at 98% using "Score All" to apply a non-FastGentleBoosting model

### ISSUE THREAD

**Issue by bfeng0** [CellProfiler/CellProfiler-Analyst#220]
Hi All-

I've created a training set and trained models using the FGB, LR and RF methods.  When I use "Score All" to apply the FGB model, the data are computed in somewhere between 10-20 minutes.  However, when I try to apply the LR or RF models, the data take 2+ hours to compute, and progress stops at 98%.  

My terminal displays an error when progress stopped: it begins to complain that the Training set could not be saved.

Here is my terminal output.  You can see when progress stops  at 12:57:47.  The error continues, and the integer keeps incrementing until I finally killed it around number 17.

[error_message.txt](https://github.com/CellProfiler/CellProfiler-Analyst/files/409977/error_message.txt)

I would have liked to have tried to test this with the nightly build but I encountered the issue described in #219.

**Comment by bfeng0** [comment]
An update-  These scoring runs are actually completing, however, I've seen with two different models that the "counter" that was in the above error message has to increment to 60 before the run will complete.  This is making for computations that last 4-5 hours.  Is this expected? Or is this some sort of timeout that's being triggered?

**Comment by daviddao** [comment]
@bfeng0 Thanks for this issue! I see, the index is _actually the true progress_ (see here: https://github.com/CellProfiler/CellProfiler-Analyst/blob/master/cpa/multiclasssql.py#L80), counting how many loops of data have been analyzed.

This issue highlights multiple problems: 

- Progress bar shows wrong progress
- Performance problem (Score-All for GeneralClassifier takes 5-6h while FGB takes only 20min)

@jhung0 I barely remember that you wrote that part, can you comment on this?

**Comment by jhung0** [comment]
I don't see that behavior, but you can try 6bb5be3608fc852413a19f07e5055762574197ca. 
FGB is faster because it makes predictions on the database side without having to fetch the data and then write back to the database.

**Comment by bfeng0** [comment]
I'll try the nightly build and see if it's any better.  My database has grown to ~3 gigs now and so far the progress indicator has been stuck at 99% for 18 hours now! This is for the Random Forest classifier.

I'm on iteration 87 according to my console.  Any way of knowing how many iterations are expected?

Thanks,
Brian

**Comment by jhung0** [comment]
Well, in my new version there are no iterations. See how that works.

**Comment by bfeng0** [comment]
Sorry for the naive question: Is there a way for me to test this without building CPA locally?

I've been downloading the "nightly" builds from:
http://d1zymp9ayga15t.cloudfront.net/CellProfiler-Analyst-nightly.dmg

...but that link hasn't been updated since September 2nd.

Thanks,
-Brian

**Comment by jhung0** [comment]
Oh good question. I'll check why it hasn't been updating. Yes, you can git
clone from source to use the latest versions (
https://help.github.com/articles/cloning-a-repository/). When you clone it
to some place on your local computer, you can then run it:
cd CellProfiler-Analyst
python CellProfiler-Analyst.py

If it doesn't work, you may be missing some dependencies. Let me know if
that works for you or not.

**Comment by jhung0** [comment]
Any update on this?

**Comment by jhung0** [comment]
@bfeng0 We're really interested talking to you about how you use it, what problems you're working on, and what you'd like to see in the future. 
If you have 15 minutes, it'd be great to chat.

**Comment by bfeng0** [comment]
Hi! I've stopped using cellprofiler analyst, but would be happy to chat about what my applications are.  How do you want to get in touch?
