### ISSUE TITLE
Allow auto-width sizing for all columns in tables 

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler-Analyst#221]
Table columns from both Classifier Hit Tables or Table Viewer (are there others?) often look like this below, i.e. the column widths are too narrow.
 ![image](https://cloud.githubusercontent.com/assets/1225595/17783491/5553cb98-6546-11e6-9072-8ed83f7bb6a4.png)

Yes, one can painstakingly mouse over the column header divider and double-click it to auto size which is useful, but I have yet to find a way to be able to auto-size all columns at once.

**Comment by braymp** [comment]
I thought View > Column widths > Fit to table did this? (Although I think you have to widen the UI first before selecting this option...)

**Comment by dlogan** [comment]
@braymp I forgot about that!  However it does exactly opposite of what I want, and made the problem worse:
![image](https://cloud.githubusercontent.com/assets/1225595/17786061/39e7c912-6551-11e6-9a40-09f2835883aa.png)
It seems to be trying to fit all the columns in the viewable space, rather than expand each column to fit the header text. Unfortunately CP database tables are nearly always very wide, both in the number of columns and the number of characters in each column header.

**Comment by jhung0** [comment]
try with cd06f96

**Comment by jhung0** [comment]
Is it ok now?

**Comment by DavidStirling** [comment]
Looks like this is fixed
