### ISSUE TITLE
Selection Ability in Plots Not Available (CellProfiler-Analyst)

### ISSUE THREAD

**Issue by srcarter3** [CellProfiler/CellProfiler-Analyst#223]
Hi there,

I noticed with the most recent stable build of CPA that there is no selection functionality in any of the plots.  I would really like to select and highlight different populations and see their correlation on different plots.  Is there any timeframe for when this functionality will be available again (from my understanding it was available in previous versions of CPA).

Thank you.

**Comment by daviddao** [comment]
Hi, 
Thanks for your request.
We are working on reenabling the lasso tool in issue #167 .

It is on our to-do list and I will keep you updated as soon as I know more about the timeframe.

**Comment by AnneCarpenter** [comment]
Closing this one as a duplicate. Please keep an eye on #167 for progress.
