### ISSUE TITLE
Allow saving thumbnails as PNG or TIF

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler-Analyst#227]
As originally mentioned in #80 

In classifier or image gallery you can go to Advanced->Save Thumbnails as JPG, but those obviously aren't ideal for downstream machine learning applications. Maybe that code could be modified to create TIFs too? Or maybe PNG because they are lossless compressed?

Any discussion or enthusiasm on this?

**Comment by daviddao** [comment]
I never thought that the thumbnail saving functionality would be so useful :) (originally I implemented it for my deep learning research). It will take a look on how to save it in PNG or TIF.

**Comment by jhung0** [comment]
I think this is done
