### ISSUE TITLE
Reinstate Rule# vs. Accuracy Plot

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler-Analyst#231]
This plot is not available any more in CPA, I think?
![image](https://cloud.githubusercontent.com/assets/1225595/18410495/c4b3d6ce-7732-11e6-9dff-98a7a6ff13ed.png)

At the very least, remove this plot from the CPA manual here:
http://cellprofiler.org/CPA/5_classifier.html#v-b-5-find-rules-training-classifier

**BUT** I'd rather have the functionality reinstated!
From a user's perspective, two questions arise, which this plot at least attempted to answer:

1. How many Rules do I need?
1. How large does my training set need to be?

Essentially (to my understanding), the function just ran cross-validation many times, with increasing numbers of rules (answering question # 1 above), and also doing 50/50, or 90/10 cross-validation (answering # 2 above).

**Comment by daviddao** [comment]
Sounds good. I will reinstate it for the FastGentleBoosting algorithm.

**Comment by dlogan** [comment]
I may have spoken too soon!  I just tried Evaluation (Menu item) > Classification Report and it gave me the old Rule# vs. Accuracy Plot.  I am using CPA 2.2.1 compiled (I can't find a git version hash?), so presumably this was always there.  Feel free to Close this if it sounds right to you.

**Comment by daviddao** [comment]
Great! :)
