### ISSUE TITLE
Wiki links dead

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler-Analyst#233]
A couple links near the top here (https://github.com/CellProfiler/CellProfiler-Analyst/wiki/CellProfiler-Analyst-Developer's-version-installation-for-Mac) are dead, namely the virtualenv links.  Probably due to a CP wiki restructuring, but in any case they would be useful links to have.

**Comment by jhung0** [comment]
I just got rid of the virtualenv part because I don't know where those
pages are now.

**Comment by dlogan** [comment]
That's one way to deal with it!  😜 
OK - I'm trying to get the vagrant solution to work.
