### ISSUE TITLE
CPA dev error: "ImportError: No module named aui"

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler-Analyst#235]
I've tried many ways to get CPA dev environment configured  on Mac and always fail.
Here I am trying virtualenv, then pip install all the files in https://github.com/CellProfiler/CellProfiler-Analyst/blob/master/requirements.txt
no problem.

But I get this:

```
$ python CellProfiler-Analyst/CellProfiler-Analyst.py
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
INFO:root:No PIL.ArgImagePlugin
Traceback (most recent call last):
  File "CellProfiler-Analyst/CellProfiler-Analyst.py", line 81, in <module>
    from cpa.classifier import Classifier
  File "/Users/logand05/Projects_local/CellProfiler_Analyst_venv_DEV/CellProfiler-Analyst/cpa/classifier.py", line 32, in <module>
    from dimensredux import PlotMain
  File "/Users/logand05/Projects_local/CellProfiler_Analyst_venv_DEV/CellProfiler-Analyst/cpa/dimensredux.py", line 26, in <module>
    import wx.aui
ImportError: No module named aui
```

I then did 
`pip install wxpython` successfully.
Same error.

I then did 
`pip install wx` successfully.
Same error.

Help?

**Comment by jhung0** [comment]
Do you know the versions?

**Comment by dlogan** [comment]
```
$ pip freeze | grep wx
wxPython==3.0.0.0
wxPython-common==3.0.0.0
wxPython-Phoenix==3.0.3
```

**Comment by jhung0** [comment]
Ok...I'm having issues too (but a different one)

**Comment by dlogan** [comment]
#236

**Comment by dlogan** [comment]
yeah, my best guess is that this may be a wxpython 3.0+ issue (vs. 2.8?).  I started to go sdown the rabbit hole and these changes in `cpa/dimensredux.py` are a start and seem to work:
```
-import wx.aui
-from wx.combo import OwnerDrawnComboBox as ComboBox
+import wx.lib.agw.aui
+from wx.adv import OwnerDrawnComboBox as ComboBox
```

But there are wx.combo import errors after that.  So should I uninstall wx 3.0 and re-install maybe, wx 2.8?

**Comment by daviddao** [comment]
I see, I am not sure, if fixing the version to 2.8 is the correct choice. Do you want to submit a PR for your changes? Thanks for going down the rabbit hole. I was there, it's really dark.

**Comment by dlogan** [comment]
Sure, I can do a PR, though it does not work yet.  I will see if I can get it to work and certainly do a PR then.

**Comment by jhung0** [comment]
Yes, that's what I would try.

**Comment by 0x00b1** [comment]
`$ pip install wxpython`? Do you mean `$ brew install wxpython`?

**Comment by dlogan** [comment]
Yeah, @0x00b1 I tried both `pip` and `brew`.  I glean that brew is more reliable for wxpython.  Unfortunately neither I nor @jhung0 can find out how to brew install any wxpython earlier than 3.0.2.  e.g. it's not listed here (https://github.com/Homebrew/homebrew-versions).   Advice?
