### ISSUE TITLE
FeatureRequest: Object Filters 

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler-Analyst#238]
Right now it seems like filters are only explicitly supported on the image level and above, and while you can always numerically gate objects it'd be great if you could filter objects based on a string.  Particularly this could be useful for making scatter plots, histograms, etc after classification- it's not unreasonable that someone might want to just look at the information about specific subclasses.  Right now you can get the specific values you want from the SQL query tool by doing something like 

```
SELECT SampleObject_AreaShape_Area
FROM ExperimentLabel_PerSampleObject INNER JOIN ClassTable 
ON ClassTable.SampleObject_Number_Object_Number = ExperimentLabel_PerSampleObject.SampleObject_Number_Object_Number 
AND ClassTable.ImageNumber = ExperimentLabel_PerSampleObject.ImageNumber 
WHERE "class" LIKE "positive";
```

but a) then you need to make a class table, which I know at least @jhung0 is leery about (not without reason) and b) I think it'd be really helpful to have them for downstream plotting functions as well.

**Comment by jhung0** [comment]
Added option to use object table in filters d366008
Do you think adding the class table too would be good?

**Comment by bethac07** [comment]
I think that the ability to graph different classes would be :1st_place_medal: , but it depends how difficult it makes your life.

**Comment by jhung0** [comment]
8d5e3a2 
I think you can make a filter with the class table if it's defined but didn't try it

**Comment by DavidStirling** [comment]
Gates now work as object filters. Doing this with normal filters won't be possible without a major rewrite, so let's close this for now and see how we get on with the new setup.
