### ISSUE TITLE
ERROR message on properties file open

### ISSUE THREAD

**Issue by jhung0** [CellProfiler/CellProfiler-Analyst#239]
From http://forum.cellprofiler.org/t/analyst-error-message-on-properties-file-open/4122
Hi,

I'm using a Mac Pro running Sierra (however I had this problem also with earlier MacOS versions..) and I cannot open any properties files with Analyst. I have tried all possible versions of Analyst available for download on your website but I always have the same problem: the software starts, but as I click on the properties file I want to open (no matter which file) I get (pretty vague) the error message attached.

the console says this:
/Library/Java/JavaVirtualMachines/jdk1.8.0_73.jdk/Contents/Home
com.apple.message.domain: com.apple.java.usage.CommandLine_JavaHome
com.apple.message.domain.version: 11M4833
com.apple.message.signature: task:CommandLine version:(null) arch:x86_64
com.apple.message.value: 2
SenderMachUUID: BBFA0F6C-DA52-32C5-A2F3-0F59505D2E0B

Following suggestions on your forum I have upgraded to the latest Java version with no effect.
I also have Parallels installed on my Mac and I have to say that Analyst runs smoothly under Windows 7 using Parallels, which is per se solving my problem but I'd like to be able to go through my data without necessarily running Windows all the time..

Thanks

matteo

**Comment by jhung0** [comment]
@daviddao some kind of java error? Otherwise I have no idea

**Comment by DavidStirling** [comment]
Closing as stale
