### ISSUE TITLE
Modify show_images_from_gate/show_objects_from_gate dialog?

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler-Analyst#241]
Ordinarily when you have a histogram, scatter, or density plot and you draw a gate on it, you can right-click/ctl-click and get a menu of choices that says (among other things) 'Show images in gate', which opens a bunch of individual image viewer windows for the images that contain the objects, and 'Show [objectname] in gate', which opens a single CellMontageFrame that contains thumbnails of each object.  This is generally all well and good, but when doing per-image classification it means you have two menu options saying 'Show images in gate' that have two different behaviors (it took me forever to figure that out btw).  

It'd be clunky, but could we edit the dialog for one of these functions?  Would people be opposed to 'Show montage of [objectname] in gate' for the show_objects_from_gate text function, or does anyone have a better idea?

**Comment by jhung0** [comment]
Oh what are the 2 different behaviors? I didn't think about this when making image classification.

**Comment by bethac07** [comment]
One opens the individual images, one opens the CellMontageFrame with thumbnails.  It's nice to have the options for the two different behaviors, we should just have different wording in the menu so that you know which is which.

**Comment by jhung0** [comment]
I changed it so that there's one that says (montage) at the end 80f7807

**Comment by bethac07** [comment]
Looks great, thanks!
