### ISSUE TITLE
FeatureRequest- Turn gates into filters

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler-Analyst#243]
Right now if I gate images or objects in a plotting tool, I can use those gates on other plots and in the PlateViewer but I can't use them in the ImageGallery or the Classifier, and I can't use information from multiple gates simultaneously (ie I'd like see the cells in Gate A OR Gate B).  You could solve both of these simultaneously by being able to create filters from gates-gates and filters are both SQL queries, and the fact that gates can be used as filters on other plots should mean their data structure is close enough that it's possible.

**Comment by jhung0** [comment]
try it out in d366008

**Comment by bethac07** [comment]
Trying to open the gate in Classifier fails:
```
An error occurred in the program:
Exception: Filter query failed for filter "PLL_DNA_Low". Check the MySQL syntax in your properties file.

Traceback (most recent call last):
  File "C:\Users\bcimini\GitHub\CellProfiler-Analyst\cpa\classifier.py", line 906, in OnFetch
    filteredImKeys = db.GetFilteredImages(fltr_sel)
  File "C:\Users\bcimini\GitHub\CellProfiler-Analyst\cpa\dbconnect.py", line 787, in GetFilteredImages
    raise Exception, 'Filter query failed for filter "%s". Check the MySQL syntax in your properties file.'%(filter_name)
```

Gate syntax looks alright to me (and works in the plots):

```
Batch1_QC_Per_Image.Image_Group_Index BETWEEN "16.9578380468" AND "14428.4890135" AND Batch1_QC_Per_Image.Image_ImageQuality_PowerLogLogSlope_OrigDNA BETWEEN "-3.10738768992" AND "-2.45874194628"
```

**Comment by jhung0** [comment]
Does this happen if you try different features? Mine is working

> test per_object.Nuclei_AreaShape_Zernike0_0 >="432.191032258" AND  per_object.Nuclei_AreaShape_Zernike0_0 <="556.737967742" AND per_object.Nuclei_AreaShape_Zernike3_1 >="76.0134541621" AND  per_object.Nuclei_AreaShape_Zernike3_1 <="100.396767423"

> test2 per_image.ImageNumber >="181.627741935" AND  per_image.ImageNumber <="194.340870968"
