### ISSUE TITLE
Limitation in size of the database

### ISSUE THREAD

**Issue by beghin** [CellProfiler/CellProfiler-Analyst#245]
Dear CPA developers,

Is there and what is the size limitation of a .CSV that could be import into CPA ? Is it in term of number of objects (rows) or features (columns) or both ?

Thanks a lot 

Cheers
Anne

**Comment by jhung0** [comment]
@daviddao did we test this?

**Comment by daviddao** [comment]
We didn't test it, there are no constraints in the code, thus I think it is dependent on your machine.

**Comment by jhung0** [comment]
@beghin  We're really interested talking to you about how you use it, what problems you're working on, and what you'd like to see in the future.
If you have 15 minutes, it'd be great to chat.
