### ISSUE TITLE
Opening bioformats Images

### ISSUE THREAD

**Issue by bmemq** [CellProfiler/CellProfiler-Analyst#252]
Hi, I'm new to the Cell profiler, How you process/open bioformats files such as .svs. 

I get this error 
![untitled](https://user-images.githubusercontent.com/32114914/30757849-01ff078a-9f85-11e7-8844-9535707cb144.png)

**Comment by jhung0** [comment]
Looks like you're looking for https://github.com/CellProfiler/CellProfiler. You can also go to the forums http://forum.cellprofiler.org/
