### ISSUE TITLE
Undefined name: 'afraser'

### ISSUE THREAD

**Issue by cclauss** [CellProfiler/CellProfiler-Analyst#262]
@afraser Was this meant to mark an open TODO?
* https://github.com/CellProfiler/CellProfiler-Analyst/blob/master/cpa/boxplot.py#L397

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./cpa/boxplot.py:397:9: F821 undefined name 'afraser'
        afraser
        ^
```

**Comment by afraser** [comment]
Very unlikely based on what the code there does. I most likely thought I had switched applications and typed my username into the editor by accident.
