### ISSUE TITLE
Error in ScoreAll when no group is selected

### ISSUE THREAD

**Issue by jkh1** [CellProfiler/CellProfiler-Analyst#266]
In Classifier Score All, grouping seems mandatory even though the user has the option of not selecting a group. When no grouping is selected, CPA throws IndexError: tuple index out of range presumably trying to access a non-existent group.
This behaviour is non-intuitive as by selecting a group one would expect to get per object stats for the entire experiment. I would suggest to either warn the user if no group is selected (and/or throw an explicit error message) or allow no grouping.

**Comment by aktgpt** [comment]
Any update on this if someone doesn't want to use grouping, i.e., get per cell classification.

**Comment by DavidStirling** [comment]
Appears to be fixed in 3.0, feel free to re-open if this is still a problem.
