### ISSUE TITLE
Can't fetch images in classifier

### ISSUE THREAD

**Issue by HsnAtwi** [CellProfiler/CellProfiler-Analyst#268]
I have set the properties file according to the documentation and here it is:

# ==== Database Info ==== 
db_type     = sqlite
image_csv_file   = C:\Users\HP\Desktop\HIWI\my_example\per_image.csv
object_csv_file  = C:\Users\HP\Desktop\HIWI\my_example\per_object.csv

# ==== Table info ==== 
image_table  = per_image
object_table = per_object

# ==== Column info ==== 
image_id   = ImageNumber
object_id  = ObjectNumber
#plate_id   = plate
#well_id    = well
cell_x_loc = Particle_Location_CenterX
cell_y_loc = Particle_Location_CenterY

# ==== Image access info ==== 
image_url_prepend = C:\Users\HP\Desktop\HIWI\my_example

# ==== Image Path and Filename Columns ====
image_path_cols = Image_Pathname
image_file_cols = Image_Filename
#image_names = Actin
image_channel_colors = red

# ==== Dynamic Groups ====
#group_SQL_XXX      = MySQL select statement that returns image keys and group keys

# ==== Image Filters ====
#filter_SQL_XXX     = MySQL select statement that returns image keys you wish to filter out

# ==== Meta data ==== 
#object_name = cell, cells
#plate_type  = 96

# ==== Classify ==== 
#classifier_ignore_columns = Nuclei_Location.*, Meta.*,

# ==== Auto Load Training Set ====
training_set = MyTrainingSet.txt

# ==== alternate column area ====
area_scoring_column = Total_Object_Area

# ==== Other ==== 
#image_size = 200 # how large the thumbnail of the field of view should be
check_tables = no
image_tile_size   = 40

now I want to use the classifier but I'm getting the following error when I'm trying to fetch the objects:
An error occurred in the program:
DBException: ERROR: Database query failed for connection "MainThread" and failed to reconnect
Query was: "SELECT per_object.ImageNumber, COUNT(per_object.ObjectNumber) FROM per_object GROUP BY per_object.ImageNumber"
First exception was: no such table: per_object
Second exception was: ERROR: Database query failed for connection "MainThread"
Query was: "SELECT per_object.ImageNumber, COUNT(per_object.ObjectNumber) FROM per_object GROUP BY per_object.ImageNumber"
Exception was: no such table: per_object

Traceback (most recent call last):
  File "cpa\classifier.pyc", line 893, in OnFetch
  File "cpa\datamodel.pyc", line 117, in GetRandomObjects
  File "cpa\datamodel.pyc", line 83, in _if_empty_populate
  File "cpa\datamodel.pyc", line 57, in PopulateModel
  File "cpa\dbconnect.pyc", line 624, in GetPerImageObjectCounts
  File "cpa\dbconnect.pyc", line 64, in fn
  File "cpa\dbconnect.pyc", line 525, in execute

I'm still new to CPA and I don't really know what to do.

I have in my main folder, 2 csv files with names "per_image" and "per_object" which I filled them manually using Microsoft Excel then saved them as csv files.

What is specifically meant by the image_table and object_table in the properties file?
Did I miss something?

Any help would be appreciated.

**Comment by AnneCarpenter** [comment]
Usually people use the output of CellProfiler, which automatically produces a suitable properties file in the Export To Database module IIRC. Is there a reason you aren't using CellProfiler? Because one workaround would be to make a mock pipeline there that would produce the right file. Or, you can use the example CPA properties file from the CellProfiler.org site? 

I'm not super familiar with using csv's directly. 

One more idea is to post your question to forum.Image.sc which has more traffic (just be sure to link to here so people can find any useful replies).

**Comment by HsnAtwi** [comment]
I'm trying to use Cell profiler and/or cell profiler analyst for a slightly different purpose, my objective is to detect water particles in an image and get the average radius and so on.. but I'm still new to all of this which is making it a bit difficult. 

I found the previous error and now the classifier is fetching the images, I tried to train then evaluate but I don't really know what's happening, the Score Image is also giving me an error... 

I tried to work with Cell profiler as well but these several small windows are not appearing and I didn't know what to do after saving the project...

**Comment by AnneCarpenter** [comment]
You need to process images using CellProfiler first, and use ExportToDatabase to produce the files that CellProfiler Analyst needs to do the sorting. You can check out CPA's manual here; it's not lengthy and will get you started: https://cellprofiler.org/cpa/

Go ahead and post some of your images and explain what you are trying to accomplish over at forum.image.sc and the community can help you get started!
