### ISSUE TITLE
Mac OS Installation issue error is not descriptive

### ISSUE THREAD

**Issue by NasimJ** [CellProfiler/CellProfiler-Analyst#270]
When trying to run CPA on Mac with Java higher than 8, you see this error:
<img width="438" alt="Screen Shot 2020-02-07 at 3 21 24 PM" src="https://user-images.githubusercontent.com/55710463/74178892-5eacfa80-4c0a-11ea-845d-a51eb13f16c1.png">
It's not very descriptive.

**Comment by CBischke** [comment]
I know the thread is a bit old, but I solved this error by following steps on this page:
https://cellprofileranalyst.org/mac-installation

**Comment by andreaquezada** [comment]
Hello CBischke. I had the same issue and I solved it the first time following the instructions of the link you kindly provided. But is not working anymore. Did you resolve it permanently? I would appreciate if you could give any other feedback about this issue.

Thanks!

> I know the thread is a bit old, but I solved this error by following steps on this page:
> https://cellprofileranalyst.org/mac-installation
