### ISSUE TITLE
How to use cellprofiler analysis data in cellprofiler analyst?

### ISSUE THREAD

**Issue by mamunbtgeiu** [CellProfiler/CellProfiler-Analyst#316]
Hi,
I am a very new user of cellprofiler and cellprofiler-analyst. I could analyze my images and export them to spreadsheets, but I could not be able to use this data on cellprofile-analyst. What do I need to do? When I tried to export to the database, it did not work. I am not good at these types of job as I know extraordinarily little.
Please guide me on how to do the analysis from the beginning to the end.
Do I need any additional Software to export to the database? 
How to use MySQL? How to set up it?
How to import the analyzed data on cellprofiler-analyst?

I am using both Windows PC and mac PC. Please let me know if there is any difference between them.

Thank you very much in advance.

**Comment by DavidStirling** [comment]
Hi @mamunbtgeiu,

I suggest you take a look at [this video](https://www.youtube.com/watch?v=4aKRKrmzf60), it should guide you through the basics.

You should be able to use SQLite mode in ExportToDatabase, so there's no need for a full MySQL server.

There's also a guide [here](https://carpenter-singh-lab.broadinstitute.org/blog/help-i-want-use-cellprofiler-analyst-i-ran-my-pipeline-exporttospreadsheet) on how to convert csvs made with ExportToSpreadsheet for use with Analyst.

Hope that helps

**Comment by mamunbtgeiu** [comment]
Wow!!  Thank you so much DavidStirling. 
That means I don't need to install any additional software to export my data using SQLite mode in ExportToDatabase? Or I need some partial server? 
I will try this way. I will let you know if I could succeed in my project.

**Comment by DavidStirling** [comment]
You don't need any extra software, SQLite stores a database into a file rather than a server.

Good luck!

**Comment by mamunbtgeiu** [comment]
Thank you very much David. Do I need to install DB Browser for SQLite? Or I can use just by installing cellprofiler and cellprofiler analyst? Is there any specific settings in cellprofiler that I need to remember to do to export to the database?

**Comment by DavidStirling** [comment]
DB Browser For SQLite is a tool for viewing SQLite databases outside of CellProfiler Analyst. You don't need it to use the software. As long as ExportToDatabase is in SQLite mode and 'Create CPA Properties file' is enabled in that module you should be good to go.

**Comment by mamunbtgeiu** [comment]
Oh! I see!! 
Thank you very much for your support. I will contact you if I feel any trouble.
