### ISSUE TITLE
SVM training fails when one or more feature has only one value

### ISSUE THREAD

**Issue by ljosa** [CellProfiler/CellProfiler-Analyst#32]
The support vector machine classifier fails to train using the example dataset and example training set. The message “ValueError: Array contains NaN or infinity” appears.

I think this happens because one or more columns has only one value. The ScaleData method then introduces NaNs into the `self.svm_train_values` array.

The fix would probably be to have ScaleData remove columns that only contain one value.

**Comment by jhung0** [comment]
deprecated- SVM implemented with sklearn now
