### ISSUE TITLE
make training sets saveable even if connection to DB is lost

### ISSUE THREAD

**Issue by thouis** [CellProfiler/CellProfiler-Analyst#4]
If the DB goes away, training can hang, and saving the training set can become impossible because it relies on being able to talk to the DB.  All of the information for saving is available outside the DB, so we should make saving more robust.

**Comment by dlogan** [comment]
Yes, I hate this error below, which happens if you leave up CPA for a little while and then are unsure whether you have saved the latest training set.  It would be great to make saving training sets not depend on the MySQL connection.
```
An error occurred in the program:
DBException: ERROR: Database query failed for connection "MainThread" and failed to reconnect
Query was: "select UPDATE_TIME from INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='AssayDev_CP_only_Seeding_v1_Per_Object' and TABLE_SCHEMA='2007_11_07_Hepatotoxicity_1'"
First exception was: (2006, 'MySQL server has gone away')
Second exception was: 


Traceback (most recent call last):
  File "classifier.pyc", line 786, in OnSaveTrainingSet
  File "classifier.pyc", line 797, in SaveTrainingSet
  File "classifier.pyc", line 803, in SaveTrainingSetAs
  File "trainingset.pyc", line 47, in Create
  File "trainingset.pyc", line 36, in Clear
  File "trainingset.pyc", line 227, in clear_if_objects_modified
  File "dbconnect.pyc", line 1638, in verify_objects_modify_date_earlier
  File "dbconnect.pyc", line 1633, in get_objects_modify_date
  File "dbconnect.pyc", line 64, in fn
  File "dbconnect.pyc", line 512, in execute
```

**Comment by braymp** [comment]
Multiple +1's from me.

**Comment by daviddao** [comment]
There will be an autosave option in the next CPA release (do you think every 5min is fine?). @ljosa  currently, when CPA saves the Training Set, it also saves (besides the object key) the X and Y coordinates of the object into a txt file. However, this requires DB access and is not required for anything else (as far as I know). Can I just remove it or is it needed somewhere else?

**Comment by jhung0** [comment]
Saving the training set as a CSV works (without the DB connection), so I'd say we can make that the only option

**Comment by ljosa** [comment]
The coordinates are saved so that it's possible to convert the training set for use with a new dataset where the IDs have changed. We've used this when it's necessary to reanalyze an image set with different thresholds or segmentation parameters.

**Comment by LeeKamentsky** [comment]
I'm a little naive in this regard, but perhaps the code can be reworked:

* so that the X/Y position isn't saved if the DB is not available (e.g. try clause to fetch, except clause to set X and Y to NaN
* so that the X/Y position is attached to the in-memory data structure that holds the image and object numbers, allowing the code that writes the training set to do without the DB fetch at that point.

Either of those would work, I'm guessing. The second one obviously is a better outcome but the first might be less work.

**Comment by daviddao** [comment]
@LeeKamentsky that is not naive at all - I implemented the second proposal on top of the autosave functionality
