### ISSUE TITLE
Thumbnails in Classifier do not display

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler-Analyst#46]
Using this example properties file on Mac: https://vc.broadinstitute.org/CellProfiler/trunk/ExampleImages/cpa_example2/

fetched thumbnails do not display.  They do in CP 11710 (see screenshot of both versions below)
![screen shot 2014-05-09 at 3 40 18 pm](https://cloud.githubusercontent.com/assets/1225595/2932561/8d4bb8f4-d7b2-11e3-888f-e9686ec260ee.png)

**Comment by daviddao** [comment]
Works on Mac OS with CPA 2.2.0 
![screen shot 2016-01-20 at 5 30 50 pm](https://cloud.githubusercontent.com/assets/1241240/12465381/b73112ea-bf9b-11e5-9f53-a3c5f9776182.png)

**Comment by dlogan** [comment]
:+1:
