### ISSUE TITLE
Without Java, CPA hangs

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler-Analyst#5]
Loading images into Classifier on a machine without Java warns the user that Bioformats uses Java, though CPA will still work. However, when the "OK" is clicked in that warning dialog, CPA hangs.

**Comment by daviddao** [comment]
Happens also on Mac OS when the latest JDK version is not installed: 
![screen shot 2016-01-13 at 5 44 09 pm](https://cloud.githubusercontent.com/assets/1241240/12331690/9ca589ca-bab8-11e5-8b00-0a25638f07cf.png)

**Comment by ljosa** [comment]
I think we figured out all the build stuff to get this right for CP but didn't apply it to CPA.

**Comment by AnneCarpenter** [comment]
See also #75 ?

**Comment by AnneCarpenter** [comment]
Oops, didn't mean to assign @daviddao ... just meant to ask whether this is still a problem?

**Comment by burgerga** [comment]
Without Java, CPA 2.2.1 doesn't even start, this is the log file:

```
No handlers could be found for logger "javabridge.locate"
Traceback (most recent call last):
  File "CellProfiler-Analyst.py", line 19, in <module>
  File "javabridge\__init__.pyc", line 28, in <module>
    Copyright (c) 2009-2013 Broad Institute
  File "javabridge\jutil.pyc", line 137, in <module>
    the script has run, the values of these
  File "javabridge\jutil.pyc", line 125, in _find_jvm
    
javabridge.jutil.JVMNotFoundError: Can't find the Java Virtual Machine
```

**Comment by SahaRahul** [comment]
I tried the latest Beta version and change the path of installation to program file rather that program filex86. It worked out.

**Comment by prionbrain** [comment]
Has anyone lately checked on this issue, since Java is no longer free for use? Can anyone work on how to start using CPA without Java again - or somehow package them together - I don't know how this works but I know I am not allowed to install JVM for free anymore. That means CPA is no longer free either?

**Comment by bethac07** [comment]
You can use AdoptOpenJDK8, but CPA always does require some Java.

**Comment by DavidStirling** [comment]
As of 3.0 Java is no longer absolutely required to launch CPA,  you only need it if using the Bioformats loader. Closing this.
