### ISSUE TITLE
Have cross-validation iterate N times, display with error bars

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler-Analyst#57]
Suggestion from Carolina: 
As it stands right now, the "Check progress" cross-validation performs the operation 10 times and shows only the average.
Have the "Check progress" cross-validation button prompt for the number of times to iterate the operation for each number of rules, then display the average with error bars.

**Comment by AnneCarpenter** [comment]
Would be nice, adding 'future consideration' label.
