### ISSUE TITLE
Compiled version: log4j warning

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler-Analyst#58]
When starting the Tracer build, the following msg appears in the terminal:
```
log4j:WARN No appenders could be found for logger (loci.common.NIOByteBufferProvider)
log4j:WARN Please initialize the log4j system properly.
```
Everything works fine otherwise, and I assume it would crop up in the master build as well. StackOverflow has some material on this: http://stackoverflow.com/questions/12532339/no-appenders-could-be-found-for-loggerlog4j

**Comment by daviddao** [comment]
Thanks @ljosa for the demo. Solved in the next commit for master.
