### ISSUE TITLE
Test Dev CPA Linux install method

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler-Analyst#59]
A Forum user [on this Forum post](http://cellprofiler.org/forum/viewtopic.php?f=12&t=4030&p=11988&sid=262a947770cd924543fed94a537f7fcd#p11987) (Lee Zamparo) posted [this set of instructions](http://cerevisuals.wordpress.com/2014/10/17/install-cellprofileranalyst-onto-a-debian-ubuntu-workstation/) on how to get CPA compiled on Linux (cool!)  He was responding to another CPA user that wanted to do the same and who apparently also emailed me independently.

I am assigning this to Vebjorn, at least to sanity check the instructions - reassign the actual testing to someone else if you see fit, Vebjorn.

**Comment by AnneCarpenter** [comment]
We unfortunately don't maintain instructions for this on an ongoing basis (right, @jhung0 @daviddao ?) - will rely on google to point people to these instructions in case they are helpful.
