### ISSUE TITLE
Amend requirements on website to show that CPA on Mac requires X11 

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler-Analyst#61]
I received this email from a user at Whitehead:

>Hi David,
>
>Thank you for sending me the cell profiler pipeline. It seems to be working.
> 
>I just tried to install Cell Profiler analyst and it asks me to download X11 (see screenshot) from  >http://support.apple.com/en-us/HT201341 . I am using Mac Os 10.9.5. Is this expected or did I >download the wrong version of Cell Profiler Analyst? I am just asking since it does not say anything >about X11 in the installation instructions of the CPA manual. I downloaded Cell Profiler Analyst from >the Broad Webpage (filename: CPAnalyst_2.0_r11710.dmg).
> 
> Thanks again,
> Dirk

![image](https://cloud.githubusercontent.com/assets/1225595/5380115/bda6efc8-8063-11e4-8d9b-d7e59909b4a2.png)

We should change the CPA download web page to reflect this requirement.
 
Similar to #45

**Comment by AnneCarpenter** [comment]
I believe this is outdated, CPA installs fine without asking for X11 these days. Please re-open if that's not the case.
