### ISSUE TITLE
Scatter Plots are missing the "log()" annotation

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler-Analyst#63]
[This user reports](http://cellprofiler.org/forum/viewtopic.php?f=12&t=4068&p=12344&sid=1c30d9356cb52130540d027f41bb3c27#p12166) that when a log scale is chosen for Scatter Plots, the axis label does not indicate this.  Histograms do, though, and this should be standardized.

**Comment by daviddao** [comment]
<img width="712" alt="screen shot 2015-12-11 at 3 25 05 pm" src="https://cloud.githubusercontent.com/assets/1241240/11754773/852446a4-a01b-11e5-911c-f10d5a1fa41a.png">

Fixed with latest commit f6c67d2 .
