### ISSUE TITLE
Make cross-validation interpretable and more helpful especially with multi-class

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler-Analyst#65]
Cross-validation (the "Check progress" button) outputs Accuracy vs. # Rules.  But especially with multiple classes, it is not clear to the user which class needs improvement the most.  It may be that one class is really not well-defined with the available measurements or it may randomly contain less representative examples.  It would be nice if the output would guide the user or at least give a hint of which class could benefit most from a larger training set (or if there are "outlier" objects in any? Is that possible?)

I'm not clear on how best to accomplish this, though (first - check what is done in the code now!).  It could be that the problem is simply broken down into pairwise comparisons of bins and each pair's accuracy is displayed.  Likely there are smarter approaches out there. 

![screen shot 2015-02-24 at 2 31 06 pm](https://cloud.githubusercontent.com/assets/1225595/6357324/9511da82-bc31-11e4-8ff7-4b0dcf08ae49.png)

**Comment by dlogan** [comment]
practically a duplication of old #9

**Comment by daviddao** [comment]
Hopefully closed with 20da077 of confusion matrix and classification report. However, still open for more feature requests as separate issues.
