### ISSUE TITLE
Montage showing spectrum of classification results from one extreme phenotype to the other

### ISSUE THREAD

**Issue by ljosa** [CellProfiler/CellProfiler-Analyst#7]
This is a proposal for a small, new feature to CPA.

After training a classifier, it would often be useful to get a qualitative sense of how the cells change as you move from one class to the other. I propose a new feature that will pop up window and show a montage of cells (maybe using the existing cell bins) with enrichment with a spectrum of enrichment scores from the most negative to the most positive.

When there are more than two classes, each class would have its own montage-display window, with cells that score high for that class at one end, and low for that class at the other end.

Originally suggested 2010-10-06.

**Comment by AnneCarpenter** [comment]
Would be nice - marking for future consideration.
