### ISSUE TITLE
Check Progress error

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler-Analyst#70]
Error:
```
An error occurred in the program:
TypeError: 'NoneType' object is not iterable

Traceback (most recent call last):
  File "classifier.pyc", line 965, in OnCheckProgress
  File "fastgentleboosting.pyc", line 63, in CheckProgress
```

To reproduce, load: 
Prop file: https://github.com/broadinstitute/CP_projects/blob/master/ilastik_CP_AssayDev/CP_CPA/CP_CPA_only.properties
Training Set:
https://github.com/broadinstitute/CP_projects/blob/master/ilastik_CP_AssayDev/CP_CPA/TrainingSet_SinglePlate_DL_FibHep_NoOther.txt

Then choose 30 rules, Train, and Click on the Check Progress button.  After about 8-12% cross-validation progress, the above error appears.

**Comment by braymp** [comment]
I think I fixed this with f4b2389ee33ccbe12ddc7f35bbe08f0014366363 in the Tracer branch; will need to check into master.
