### ISSUE TITLE
Remove Protocol Navigator files from repo

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler-Analyst#74]
Since the PN package has its own [Github repo](https://github.com/imtiazKHAN/ProtocolNavigator), we should probably remove the associated files/icons from CPA.

**Comment by daviddao** [comment]
I wanted to clean up the code base anyway. There are a lot of files in CPA, which are not used at all by the main program. Do you remember which files are part of the PN package in CPA? Does anything in CPA depend on it? @imtiazKHAN

**Comment by braymp** [comment]
To my knowledge, nothing in CPA depends on PN.

**Comment by daviddao** [comment]
I removed all PN files (to the best of my knowledge) in the new 2.1.0-dev version and merge it into master as soon as it is production-ready.
