### ISSUE TITLE
Straighten out JDK run requirements for Tracer

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler-Analyst#75]
Some Tracer run requirements which need work:
*  The JDK (not just the JRE) is required for it to the build to run.
* I found the following re: where the JDK path (C:\Program Files\Java\jdk1.8.0_60\bin) needed to be:
 * No JDK in Path variable, and no JAVA_HOME variable yields "ImportError: DLL load failed: The specified module could not be found."
 * JDK path in JAVA_HOME only, not in Path yields "javabridge.jutil.JVMNotFoundError: Can't find the Java Virtual Machine"
 * JDK in Path variable: Tracer starts and works fine.

@LeeKamentsky says the JDK should be required to build, the JRE should be required to run and if Java was properly installed, Javabridge should be able to find it from the Windows registry.

**Comment by LeeKamentsky** [comment]
We need to find a stable link for the 64-bit Java installation. I can do a myriad of things if I have that link - launch a browser during the install to ask to install it, tell the user exactly where to get it, etc. If anyone can find a link, please tell me. The best I can do is http://www.oracle.com/technetwork/java/javase/downloads/server-jre8-downloads-2133154.html

and that doesn't seem like it will be a reliable link for any length of time.

**Comment by braymp** [comment]
Did a bit of poking around; according to [this](https://serverfault.com/questions/425056/why-i-cannot-download-jdk-from-oracle-web-site-directly-without-authparam/624391), it seems there might be no way around having to explicitly acknowledging their terms of service prior to d/l.

**Comment by LeeKamentsky** [comment]
http://java.com/en/download/manual.jsp looks like it's the best we can do. I agree, can't install w/o user's knowledge, too many reasons why that will never work.

**Comment by AnneCarpenter** [comment]
We currently instruct users to download JDK for Mac, so I think this issue can be closed.
