### ISSUE TITLE
Implement per-image classification

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler-Analyst#76]
One thing that's been left outstanding in CPA for a while is per-image classification in Classifier, which is used regularly for cell painting QC work. 

Right now, I have a solution in which I use a script to create a view of the per-image table with the addition of a ObjectNumber col (set to 1), plus X/Y location cols (set to the coords of the image center). This works OK, but is hacky.

Conceptually, adding this should be reasonably simple; all the needed info is largely specified by the properties file already.

**Comment by jhung0** [comment]
done
