### ISSUE TITLE
Save image with classification results

### ISSUE THREAD

**Issue by jhung0** [CellProfiler/CellProfiler-Analyst#80]
When scoring an image/ displaying an image's classification results, be able to save the image with classification results overlay (currently only the original image is saved)

**Comment by afolarin** [comment]
Exporting images of objects within a predefined boundingbox or an adaptive box seems like something that should be trivial. This would be very useful anyway if one wanted to create training datasets from cellprofiler for other machine learning tools -- I was very surprised to see one couldn't do this with either Cellprofiler or CellProfilerAnalyst.

**Comment by daviddao** [comment]
Its possible to export image tiles or object tiles. In classifier or image gallery go to **Advanced->Save Thumbnails as JPG**

**Comment by bethac07** [comment]
You currently can export .jpg thumbnails of all of the objects from CPA, but those obviously aren't ideal for downstream machine learning applications.  Maybe that code could be modified to create TIFs too?

**Comment by bethac07** [comment]
SaveImages doesn't actually do the creation of individual object images; would have to make it a feature request and possibly a new module.  @afolarin Wouldn't be a bad idea to request it over at CellProfiler.

**Comment by braymp** [comment]
Somewhat related: https://github.com/CellProfiler/CellProfiler/issues/229

**Comment by braymp** [comment]
Also https://github.com/CellProfiler/CellProfiler/issues/240

**Comment by AnneCarpenter** [comment]
Wow, lots of random discussions here. 

I made a feature request for CPA, Allowing saving thumbnails as PNG or TIF: #227

There is now a feature request for CellProfiler itself to export each cell as an individual image: 
https://github.com/CellProfiler/CellProfiler/issues/2255

To clarify, the original issue stated here "Save image with classification results" is not completed. It would be nice but not missions-critical. If you think it is, please comment and/or re-open!
