### ISSUE TITLE
Button to remove duplicate images 

### ISSUE THREAD

**Issue by jhung0** [CellProfiler/CellProfiler-Analyst#81]
Have the option to clear duplicate images from a class

**Comment by daviddao** [comment]
@ljosa is it intended that "Fetch data" sometimes fetches the same object key multiple times?

**Comment by ljosa** [comment]
I think @afraser implemented it that way out of convenience, with the thinking being that (1) image sets would usually be large enough that it wouldn't happen much and (2) scoring the same image twice is not necessarily a bad thing.

**Comment by afraser** [comment]
That's right. Although the second point actually has a more interesting corollary: Classifying the same image in different ways also has meaning.

It might be useful to provide a feature that points out when this sort of thing happens to help users identify their own inconsistencies, or differences in how they classify a given phenotype vs how their co-workers do (in the case where the training is being done by multiple users).

**Comment by daviddao** [comment]
Thanks for the input, i created a new issue for @afraser's suggestion: #89

**Comment by AnneCarpenter** [comment]
Removing duplicates might be handy; there is a workaround which is opening the training set and parsing the text in the file via scripts. Marking this issue for future consideration.
