### ISSUE TITLE
show table of image classification results

### ISSUE THREAD

**Issue by jhung0** [CellProfiler/CellProfiler-Analyst#83]
Right now I can't see a chart of image classification results (i.e., score image, but there is one if scoring all)

**Comment by braymp** [comment]
I use the "Classify" item in the image menu bar. The color-coded dot appears at whatever you specified for the object location. Not super-convenient but it works.

**Comment by jhung0** [comment]
yes I see the dots, but I want a count for the number of items in each class

**Comment by jhung0** [comment]
implemented in new release
