### ISSUE TITLE
Have CPA load properties without needing to restart

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler-Analyst#84]
Not sure if this is readily doable, but it would be great to have CPA start without requesting a properties file and/or be able to load a new properties file during a session.

**Comment by AnneCarpenter** [comment]
This has been requested a lot, is a new-user understandability issue, and is worth doing.

**Comment by DavidStirling** [comment]
Done. CPA will prompt for a properties file on opening, but won't crash if you fail to provide one or the file you provide is broken. The file menu now has an option for loading a properties file, which can be used to switch files without restarting CPA.
