### ISSUE TITLE
Allow fetching of objects near the decision boundary

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler-Analyst#87]
Form Carolina:
> I also had a suggestion from a collaborator; When training the classifier it is possible to fetch random positives/negatives etc after the first round of training. It would be great if it was possible to also fetch positives/negatives close to the decision boundaries for more exact and efficient fine-tuning.

**Comment by dlogan** [comment]
This is a good idea, especially for rare phenotypes which are less likely to get fetched randomly.  But it is not new - I found an email from Feb 2, 2010 from Ray that said:
"In any case, CPA is now able to select randomly from, load, save, and
(I hope) train from multiple tables.  The "?" button (i.e., "give me a
cell near the decision boundary") currently doesn't work for single
images or random images, but I'll fix that, soon."

I don't believe I ever saw that "?" button  (Ray? @thouis )

**Comment by daviddao** [comment]
[Subset of #60] It's a good idea, we already implemented that for the next release of CPA. We fetch uncertain images (criteria is either entropy of the probability distribution of the predicted classes, or a simple method @jhung0 proposed which measures the difference between the two closest classes (in sense of probability) and use that as threshold. I will keep it open until we finally release a new version of CPA.
