### ISSUE TITLE
Pointing out differences in manual classifications

### ISSUE THREAD

**Issue by daviddao** [CellProfiler/CellProfiler-Analyst#89]
From @afraser: 
Classifying the same object/image in different ways also has meaning.
It might be useful to provide a feature that points out when this sort of thing happens to help users identify their own inconsistencies, or differences in how they classify a given phenotype vs how their co-workers do (in the case where the training is being done by multiple users).

**Comment by afraser** [comment]
:+1:

**Comment by AnneCarpenter** [comment]
Cool, marking for future consideration.
