### ISSUE TITLE
Confusion matrix for crossvalidation

### ISSUE THREAD

**Issue by ljosa** [CellProfiler/CellProfiler-Analyst#9]
This is a proposal for a small, new feature in CPA. The current crossvalidation graph tells you how the overall accuracy changes a function of the number of features, but it does not help you understand what kinds of mistakes are being made, especially when there are mulitple classes. I propose a feature that performs leave-one-out crossvalidation, pops up a new window, and displays a confusion matrix. 

The confusion matrix should contain the percentages of each cell and could be color coded. The scale of the color bar requires some thought.

Originally suggested 2010-10-06.

**Comment by daviddao** [comment]
I love @dlogan's evaluation idea. It's on my to-do list.

**Comment by daviddao** [comment]
After commit 20da077 , this functionality is indirectly possible by 

1. training our classifier on training set A
2. removing the training set A from the bins 
3. fetching / sorting new images 
4. plotting evaluation for the newly fetched ones

After a conversation with @AnneCarpenter , we decided that this is easier and prettier than implementing an extra button for this.
