### ISSUE TITLE
Implement new properties fields: site_id, site_order, first_site

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler-Analyst#91]
Currently, CPA creates montage in PlateViewer by ordering thumbnails by ImageNumber order to as close to a square grid as it can. For our previous scope, the assumptions were satisfied and the output montage looked good.

For our new scope, the site acquisition order is different, so the montage looks funny. It would be nice for CPA to accommodate this by having a few new fields:
* site_id: Specifies the site metadata. Almost always captured in the CP pipeline, but can be left blank if none.
* site_order: Specifies acqustion order. I imagine the syntax could be a tuple of tuples, e.g., ((1,2,3),(4,5,6),(7,8,9)). If omitted or blank, CPA could perform the behavior it already had.
* first_site: Specifies what the first site ID is, in case the site is 1-based, 0-based or something else. Probably should default to '1'.

**Comment by dlogan** [comment]
Agreed that a true montage would be nice.  Is site_order meant to specify the physical position/layout?  I would assume that the order might be different for different microscope vendors and so perhaps site_x and site_y metadata might be more general?

**Comment by braymp** [comment]
Re: site_order - Yes, I was hoping that a list of tuples would specify layout. So a field specified as:
`site_order = ((1,2,3),(4,5,6),(7,8,9))` would indicate a 3 x 3 grid in which the sites first from the upper-left corner in row-major order.

**Comment by AnneCarpenter** [comment]
Would be nice, marking for future consideration.
