### ISSUE TITLE
ConfusionMatrix error

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler-Analyst#94]
In newest Mac dmg, I set Menu > Classifier = Fast Gentle Boosting, and Menu > Evaluation = Confusion Matrix.  I trained and clicked Plot Evaluation and got this eror:
```
An error occurred in the program:
AttributeError: 'FastGentleBoosting' object has no attribute 'ConfusionMatrix'

Traceback (most recent call last):
  File "/Applications/CellProfiler Analyst_2015_12_10.app/Contents/Resources/lib/python2.7/cpa/classifier.py", line 1216, in OnEvaluation
```

**Comment by daviddao** [comment]
Yes confusion matrix is not implemented (yet) for GentleBoosting. @jhung0 and I were actually thinking about deprecating GentleBoosting due to its performance and incompatibility with scikit learn but we are open for discussion.

**Comment by dlogan** [comment]
Deprecating Gentle Boosting's confusion matrix, or Gentle Boosting altogether?  For the confusion matrix, that's fine with me to not implement (or leave it for much later), but GB I think should be kept in general for backwards-compatability if nothing else

**Comment by jhung0** [comment]
It's probably ok to leave it in and just have it have fewer evaluation
options than other classifiers (also label it so people know it was from
 the old CPA). We just want to really discourage people from using it.

**Comment by braymp** [comment]
:+1: for leaving FastGentleBoosting in, as the current CPA workshop format and several outreach exercises use the easy interpretability of the decision stumps as a talking point. This is not a big deal if other classifiers can be used similarly for educational purposes, but it does mean some add'l work in re-thinking/re-writing these items.

**Comment by jhung0** [comment]
For the classifiers involving decision trees, similar rules can be extracted
http://stackoverflow.com/questions/20224526/how-to-extract-the-decision-rules-from-scikit-learn-decision-tree

**Comment by daviddao** [comment]
Added with 399def328854a5f9a53ac72d2bc9aa2892d30a8c
